### ISSUE TITLE
Examples/documentation lack several things

### ISSUE THREAD

**Issue by VanKurt** [python-caldav/caldav#107]
I just started using this library. Currently I'm having a hard time figuring out several things, and the documentation and examples don't help much. It would be great, if they could be more comprehensive.

For example:
 - How do I use the "icalendar_instance"? E.g. event.icalendar_instance.summary gives me an error 'Calendar' object has no attribute 'summary'
 - How do I get the start and end time of an event? How do I find out, if the event is an all day event? I'm sure there are properties for these information, but they seem to be not documented at all.

**Comment by tobixen** [comment]
I intentionally left out those parts, as the library is in a transition phase between using vobject instances and icalendar instances. I'm not by the keyboard now, can only suggest that you check the documentation for the icalendar and vobject libraries

**Comment by tobixen** [comment]
Still not by a keyboard, but I believe it should be `event.icalendar_instance['summary'] `

**Comment by tobixen** [comment]
And if that doesn't help, try to replace lower case summary with uppercase SUMMARY

**Comment by tobixen** [comment]
the last version of basic_usage.py covers this
