### ISSUE TITLE
Bug with URL quote/unquote

### ISSUE THREAD

**Issue by andrei-mart** [python-caldav/caldav#11]
in caldav/objects.py:
DAVObject._handle_prop_response() unqotes key it returns:
line 174:            
       href = unquote(r.find('.//' + dav.Href.tag).text)
but in DAVObject.get_properties it is compared to URL path, which is quoted:  
lines 209-218: 
        path = self.url.path
        exchange_path = self.url.path + '/'

        if path in list(properties.keys()):
            rc = properties[path]
        elif exchange_path in list(properties.keys()):
            rc = properties[exchange_path]
        else:
            raise Exception("The CalDAV server you are using has "
                            "a problem with path handling.")
So, if base path contains quoted characters, they do not match and the server is blamed.
Following modification makes it working for me:
lines 209-210: 
        path = unquote(self.url.path)
        exchange_path = path + '/'

Also, a small optimisation in lines 212 and 214:
        'in properties' is equivalent of 'in list(properties.keys())', but more effective.

**Comment by tobixen** [comment]
I'm sorry to say that I have no capacity for the foreseeable future to look into this (though I'm not able to foresee much of the future - in the very best case, perhaps I will have time in some few weeks).  Perhaps you could make a pull request?  I think it's important to include some test code that throws an error with the current code in the pull request.

I'm generally having a low threshold for accepting pull requests, though I will do more thoroughly testing before the next release.

**Comment by andrei-mart** [comment]
I am not sure I will find time to put together proper fix (with test), but I will try.

**Comment by JeyDee** [comment]
I can confirm that this solves the problem (thank you very much for this, andrei-mart).
Can you please accept the pull request, tobixen?

**Comment by tobixen** [comment]
pull request has been accepted, but I still didn't get to release a new version

**Comment by JeyDee** [comment]
OK, I see. Thanks :).

**Comment by tobixen** [comment]
I believe this was fixed and that this issue can be closed
