### ISSUE TITLE
Calendar.object_by_uid doesn't work with CRLF combination in response  

### ISSUE THREAD

**Issue by pleasedonotwatch** [python-caldav/caldav#112]
Example:
UID of event: 5a61dff2-15c4-4087-8f04-ad7ca20db0a7
Response looks like: 
...\r\nUID:5a61dff2-15c4-4087-8f04-ad7ca20db0a7\r\n...
Result of evaluation 814 string in objects.py: 
![image](https://user-images.githubusercontent.com/54893877/92494608-9579dc00-f1fe-11ea-91a8-3783faa42248.png)
So it's raises error: 
```
        for item in items_found:
            # Long uids are folded, so splice the lines together here before
            # attempting a match.
            item_uid = re.search(r'\nUID:((.|\n[ \t])*)\n', item.data)
            if (not item_uid or
                    re.sub(r'\n[ \t]', '', item_uid.group(1)) != uid):
                continue
            return item
        raise error.NotFoundError("%s not found on server" % uid)
```

**Comment by tobixen** [comment]
Should be simple enough to replace `item.data` above with `item.data.replace('\r\n', '\n')` or something like that.  And then it's needed with some test code as well.

**Comment by tobixen** [comment]
I'm not really sure that this have been fixed ... I didn't add any test code, and I'm thinking that there may be other breakages due to stray CR characters.
