### ISSUE TITLE
Get supported components from calendar?

### ISSUE THREAD

**Issue by Programie** [python-caldav/caldav#114]
AFAIK, it is not possible to get a list of supported components from a calendar.

Would it be possible to implement a method to get the supported components (i.e. a list `["VEVENT", "VTODO"]`)?

Or maybe there is another way to get the `supported-calendar-component-set` property of a calendar?

**Comment by tobixen** [comment]
There is no "high-end" api available for fetching this as for now, but possibly the get_properties method will do?  Perhaps something like `calendar.get_properties([cdav.SupportedCalendarComponentSet()])` ?  I don't have time doing research on it right now.  Eventually, I'd be happy to accept a pull request for a new method `Calendar.GetSupportedCalendarComponentSet()`, particularly if the pull request also contains some test code :-)

**Comment by Programie** [comment]
For some reason, `calendar.get_properties([cdav.SupportedCalendarComponentSet()])` only returns `None` instead of a list of components.

Executing a PROPFIND request against my CalDAV server (Nextcloud) responds with the correct `supported-calendar-component-set` properties:

```xml
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
  <d:response>
    <d:propstat>
      <d:prop>
        [...]
        <cal:supported-calendar-component-set>
          <cal:comp name="VEVENT"/>
          <cal:comp name="VTODO"/>
        </cal:supported-calendar-component-set>
        [...]
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>
```

**Comment by tobixen** [comment]
Could be an idea to turn on debug logging, run the debugger, or simply inject some print-statements into the code and see what query is sent to the caldav server when trying to do the get_properties and what kind of return we get ...

... perhaps I'll get some time to look into it later today.

**Comment by Programie** [comment]
I just turned on debug logging and tested again.

The following XML is sent as body in the PROPFIND request:

```xml
<?xml version='1.0' encoding='utf-8'?>
<D:propfind xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
    <D:prop>
        <C:supported-calendar-component-set />
    </D:prop>
</D:propfind>
```

As a result, I get an HTTP status 207 with the following XML (replaced `d:href` for privacy reasons):
```xml
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
    <d:response>
        <d:href>/remote.php/dav/calendars/myuser/some_calendar/</d:href>
        <d:propstat>
            <d:prop>
                <cal:supported-calendar-component-set>
                    <cal:comp name="VEVENT" />
                </cal:supported-calendar-component-set>
            </d:prop>
            <d:status>HTTP/1.1 200 OK</d:status>
        </d:propstat>
    </d:response>
</d:multistatus>
```

But a `print()` of the `get_properties()` result just shows a dict with the value set to `None`:
```
{'{urn:ietf:params:xml:ns:caldav}supported-calendar-component-set': None}
```

**Comment by tobixen** [comment]
if it's due to `cal:` instead of `C:`, then the bug is in the caldav library and not on the NextCloud side of things.  The bug is probably somewhere in DAVObject._handle_prop_response

**Comment by Programie** [comment]
It doesn't seem to be caused by the `cal:` instead of `C:` namespace prefix but the way, the library is getting the attribute from the `cal:comp` element.

In [caldav/objects.py#L206](https://github.com/python-caldav/caldav/blob/master/caldav/objects.py#L206), the attribute "text" is being tried to be retrieved from the element which results in `None` as there is no text attribute in the element.

While debugging, `val.attrib["name"]` actually returned the right value (e.g. "VEVENT").

`SupportedCalendarComponentSet` is extended from `ValuedBaseElement` which I understand as the value is expected in the content of the element (e.g. `<cal:supported-calendar-component-set>VEVENT</cal:supported-calendar-component-set>`). But the value is actually the `name` attribute of the `cal:comp` child element. And there might be multiple `cal:comp` elements in case the calendar supports multiple components (e.g. events and tasks).

**Comment by tobixen** [comment]
I will look into it

**Comment by tobixen** [comment]
That `_handle_prop_response` is a real mess :-(  It should probably be refactored a lot.

**Comment by tobixen** [comment]
Please check that work branch ... https://github.com/python-caldav/caldav/compare/wip_feature_get_supported_component_types

**Comment by Programie** [comment]
Cool!

`calendar.get_properties([caldav.cdav.SupportedCalendarComponentSet()])` now returns the following:

```
{'{urn:ietf:params:xml:ns:caldav}supported-calendar-component-set': {'name': 'VEVENT'}}
```

But there is one more thing: The `supported-calendar-component-set` property should be a list of component sets. For example, a calendar might support `VEVENT` as well as `VTODO`. The current implementation only seems to return the first component. In case the calendar supports events and todos, the method only returns `VEVENT`.

**Comment by tobixen** [comment]
You are doing it wrong :-) I made a separate method `calendar.get_supported_components()` for this

**Comment by Programie** [comment]
Oh right... tested it again and it works as expected. Thanks! :-)

**Comment by tobixen** [comment]
Merged to master
