### ISSUE TITLE
Unintended object mutation

### ISSUE THREAD

**Issue by andrei-mart** [python-caldav/caldav#12]
in caldav/davclient.py:
DAVClient.request lines 221-222:
        combined_headers = self.headers
        combined_headers.update(headers)
First line makes combined_headers to be a *reference* to self.headers, and therefore second line, in fact, updates self.headers with values from headers, affecting all subsequent requests.
The combined_headers should be a copy instead:
         combined_headers = dict(self.headers)
         combined_headers.update(headers)

**Comment by tobixen** [comment]
Awful, thanks for finding this.

**Comment by tobixen** [comment]
Hm, committing without running tests actually - because it's an obvious bug.  But the code and the test suite may actually be dependent on unintentional side effects, should probably revisit this when I get more time.

**Comment by tobixen** [comment]
All tests passes
