### ISSUE TITLE
save_event failing with "Component <ical> was never closed"

### ISSUE THREAD

**Issue by markditsworth** [python-caldav/caldav#129]
caldav version 0.7.1
python 3.7.3
environment: raspberry pi

Error message:
```At line 1: Component VCALENDAR       VERSION:2.0       PRODID:-//SABRE//SABRE VOBJECT 4.3.0//EN       BEGIN:VEVENT       UID:CE1EE57D86F12ED167B667C3681B738E44D72BA5       DTSTAMP:20210106T064709Z       DTSTART:20210107T200000Z       DTEND:20210107T210000Z       SUMMARY:DOCTOR APPOINTMENT       END:VEVENT       END:VCALENDAR        was never closed```

Relevant code:
```
    def makeEventString(self, name, start, end, rule=None):
        tstamp = dt.now(tz=timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        start_utc = start.astimezone(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        end_utc = end.astimezone(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        _id = hashlib.sha1(bytes(tstamp+name,'utf-8')).hexdigest()
        if rule is not None:
            rrule = "FREQ={}\n".format(rule)
        else:
            rrule = ""
        s = """BEGIN:VCALENDAR
        VERSION:2.0
        PRODID:-//Sabre//Sabre VObject 4.3.0//EN
        BEGIN:VEVENT
        UID:{}
        DTSTAMP:{}
        DTSTART:{}
        DTEND:{}
        {}SUMMARY:{}
        END:VEVENT
        END:VCALENDAR
        """.format(_id, tstamp, start_utc, end_utc, rrule, name)
        return ''.join(s.split('\t'))

    def makeEvent(self, calendarObj, start, end, name, rule=None, owner='your'):
        eventString = self.makeEventString(name, start, end, rule=rule)
        try:
            _ = calendarObj.save_event(eventString)
            
        except Exception as e:
            self.log.error(e)
```

What is this "never closed" referring to in this case? It seems like it is something to do with the ical object. I thought maybe it was the leading tab from the function indention, but removing that via splitting on '\t' did not change the error.

**Comment by tobixen** [comment]
Probably a duplicate of #106 and #80

You don't need leading tabs in a docstring.

**Comment by markditsworth** [comment]
Yep changing to 
```
        s = """BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Sabre//Sabre VObject 4.3.0//EN
BEGIN:VEVENT
UID:{}
DTSTAMP:{}
DTSTART:{}        
DTEND:{}
{}SUMMARY:{}        
END:VEVENT
END:VCALENDAR
"""
```
did the trick. Weird show stripping out the tabs didn't work. Thanks!

**Comment by tobixen** [comment]
Perhaps because the code was indented with spaces rather than tabs.  Also, you don't need to do join and split, there is always the replace method, like `"foobar".replace('o','')`.  To remove leading blanks it would probably be better to use the regexp library though.
