### ISSUE TITLE
Calendar.todos() ignores todos without status on NextCloud/OwnCloud and sabre/baikal

### ISSUE THREAD

**Issue by mayjs** [python-caldav/caldav#14]
It seems like the Nextcloud/Owncloud tasks app does not set a status on new tasks. These tasks are not returned using `Calendar.todos(include_completed=False)`. If `include_completed` is set to True, they are returned as expected.

**Comment by tobixen** [comment]
RFC says that the status is OPTIONAL, and it makes sense to assume the default is that the task is not completed - so yes, indeed, this is a bug in the caldav library.

I don't have time looking into this in the foreseeable future, but it should be trivial to fix.  Care to write up a pull request?

**Comment by mayjs** [comment]
You were right, the fix was trivial. The PR should fix this issue.

**Comment by tobixen** [comment]
I'm reopening this issue.  We need explicit test code generating todo-items without a state, and it's needed to browse through the RFC.

It may seem that there is a difference between NextCloud and DAViCal in how it interprets the XML.

A bullet-proof approach may be to do two queries, one for todos with STATE not set to COMPLETED or CANCELLED, and one for todos with STATE undefined, and then do a union of those.

**Comment by tobixen** [comment]
When reverting the commit and adding an explicit test with an object without STATE set, the tests seem to pass on zimbra, DAViCal and Bedeworks.  I will get back to NextCloud a bit later.

**Comment by tobixen** [comment]
The issue has been reproduced with the sabre/baikal server.

Ref section https://tools.ietf.org/html/rfc4791#section-7.8.9 apparently the logic in the library is right, and the sabre/nextcloud implementation is doing it wrong, though I can't see any explicit rules that a negated text match should yield true if the field is not defined.

As far as I can understand from the RFC, there is no "or" in the query language, so the proposed fix breaks querying for non-completed TODO items with STATE=NEEDS-ACTION.

The only workaround I can think of is to take out the todo-list in two operations, first to fetch all those items with STATE=NEEDS-ACTION and then fetch all items without a state.
