### ISSUE TITLE
Examples use of icalendar missing

### ISSUE THREAD

**Issue by mh-g** [python-caldav/caldav#140]
How do I convert the result of a calendar search (list of caldav.objects.Event) to icalendar.cal.Event for further processing?

**Comment by mh-g** [comment]
Scouring the unit tests of icalendar, I found and adapted to the following:
```
import icalendar
[...]
events_fetched = my_calendar.date_search(start=today(), end=date.today() + timedelta(days=7), expand=True)
for e in events_fetched:
    ev = icalendar.Calendar:from_ical(e._get_data())
    print (ev)
```

**Comment by tobixen** [comment]
This went completely under my radar.  You are not supposed to use methods starting with an underscore directly (I should eventually look into that test code).  You should do `cal = e.icalendar_instance`.  Then you can even edit the cal object and `e.save()` will catch the changes done.

Also ref #107, I should fix the basic_usage_example.py to make this clearer.
