### ISSUE TITLE
Open-Xchange: `unexpected content type from server`

### ISSUE THREAD

**Issue by Feandil** [python-caldav/caldav#142]
Hi!

While using caldav-0.8.0 against an Open-Xchange 7.10.4 server (https://oxpedia.org/wiki/index.php?title=AppSuite:Main_Page_AppSuite), I'm getting the following warnings (extract):
```
ERROR:caldav:unexpected content type from server: text/html;charset=ISO-8859-1. Please raise an issue at https://github.com/python-caldav/caldav/issues or reach out to t-caldav@tobixen.no, include this error and the traceback and tell what server you are using
ERROR:caldav:unexpected content type from server: text/html;charset=UTF-8. Please raise an issue at https://github.com/python-caldav/caldav/issues or reach out to t-caldav@tobixen.no, include this error and the traceback and tell what server you are using
```

There is however no associated traceback and the code works just fine...
I see from https://github.com/python-caldav/caldav/blob/b9c33ed9a5be83e94a7824fcfc0185048c397993/caldav/davclient.py#L44-L76 that you expect `text/xml`, `application/xml`, `text/calendar`or `text/plain`, not `text/html`.
I'll try debugging it further, but as the error message asks to `raise an issue` here, I'm doing so. ;)

**Comment by tobixen** [comment]
Hm.  Perhaps the line should simply be removed (and the whole code section should be refactored, the purpose behind the long if/elsif/else-branch there has disappeared).

I can think of two possibilities here, either that the server is passing an expected XML response but invalid content-type (the XML parsing in the try-except-block passes), or that the content is ignored by the caldav library (empty content, empty content expected, some error code - like a 404 can be an expected response sometimes).

If the server passes the wrong content-type, we ought to raise an issue at OX, otherwise the content-type should be ignored.

Can you try to figure out what's the case here?

**Comment by Feandil** [comment]
Sorry for the late update.
Adding some debugging (basic `log.error("Raw content: %s" % (self._raw.decode('UTF-8')))`), I get different errors:
- First trigger, on the request (which I guess is due to BasicAuth support only and no DigestAuth (https://github.com/python-caldav/caldav/blob/master/caldav/davclient.py#L521-L523), so handled transparently).
   ```
   <!DOCTYPE html>
   <html><head>
   <title>401 Authorization Required&#x21;</title>                           
   </head><body>
   <h1>Authorization Required&#x21;</h1>                           
   <p>Authorization Required&#x21;</p>                           
   </body></html>
   ```
- Later on:
   ```
   <!DOCTYPE html>                                                                                                                                                                                                                                             
   <html><head>                             
   <title>429 Too Many Requests - Your request is being rate limited.</title>
   </head><body>                                                             
   <h1>Too Many Requests - Your request is being rate limited.</h1>
   <p>Too Many Requests - Your request is being rate limited.</p>  
   </body></html>
   ```

The later result the corresponding `caldav.error.PutError` that I'm catching (& triggering a wait & retry), so "expected" ;)

AFAIU, that's the later of your two hypothesis.
I'm not able to find references in caldav specifications: is there an expected format for such error message (recommending XML for example)? Otherwise, would it be safe to simply skip this error (and maybe even the processing?) if it receives a 4xx?

**Comment by mhthies** [comment]
Nextcloud's CalDAV server seems to return an empty response with HTTP status code 201 and Content-Type 'text/html' upon most successful PUT actions. This is also logged as "unexpected content type from server" by python-caldav.

**Comment by tobixen** [comment]
I'll just remove the error logging as for now, though I believe I can eventually also remove quite some other silly code lines at that section and totally ignore the content-type.
