### ISSUE TITLE
Calendar class (or, DAVObject maybe) should have a get_name method

### ISSUE THREAD

**Issue by tobixen** [python-caldav/caldav#145]
I just wanted to print out the name of a calendar, but didn't have time to do any testing ... a convenience-method `get_name` would be nice.

**Comment by GUAYMI** [comment]
Someone else in the office?

I am quite lost in this app @tobixen any advice?

**Comment by tobixen** [comment]
Which office?  Which app?

**Comment by tobixen** [comment]
This has been fixed in https://github.com/python-caldav/caldav/pull/212
