### ISSUE TITLE
date_search ignoring start & end date

### ISSUE THREAD

**Issue by hitura-nobad** [python-caldav/caldav#147]
Hi,

I am trying to get a list of events from my SOGO caldav server for today, but date_search seems to be ignoring the boundaries I set him and it gives me 2 month old events.

Is this an issue with the SOGO server or am I doing something wrong here?

````
from datetime import datetime,timedelta
import caldav
import yaml
from icalendar import Calendar

CONFIG = yaml.load(open("config.yaml"), Loader=yaml.FullLoader)

client = caldav.DAVClient(url=CONFIG["caldav_url"], username=CONFIG["caldav_user"], password=CONFIG["caldav_password"])

my_principal = client.principal()
calendar = my_principal.calendar(name=CONFIG["calendar_name"])
events_fetched = calendar.date_search(start=datetime.now(),end=datetime.now(), expand=True)
for event in events_fetched:
    ical_text = event.data
    gcal = Calendar.from_ical(ical_text)
    for component in gcal.walk():
        if component.name == "VEVENT":
            print(component.get('summary'))
            print(component.get('dtstart').dt.strftime("%Y-%m-%d %H:%M"))
```
`

**Comment by tobixen** [comment]
First, if this is with release 0.8.0, then try the master branch.  I did start testing with SOGo after releasing 0.8.0, and I did some few modifications to get basic stuff to work.  Unfortunately I got my hands filled with more urgent matters, so I never got time to complete my work and do a 0.8.1-release.

**Comment by tobixen** [comment]
Second, try with a real date range, covering several days.  (I think it shouldn't matter ... but you never know)

**Comment by hitura-nobad** [comment]
I tried both, didn't fix it.

I think the issue is with weekly reccuring dates, it gives me the date of the first event instead of the event in the current date range..

I'm attaching you one of the ical events which is giving me this issue.

Am I supposed to calculate the right dates myself? I would have expected to get them delivered with the correct date instead

`BEGIN:VCALENDAR
PRODID:-//Apple Inc.//iOS 14.5//EN
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
DTSTART:19810329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
TZNAME:MESZ
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
BEGIN:STANDARD
DTSTART:19961027T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
TZNAME:MEZ
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20210501T095807Z
DTEND;TZID=Europe/Berlin:20210503T113500
DTSTAMP:20210501T095830Z
DTSTART;TZID=Europe/Berlin:20210503T095000
LAST-MODIFIED:20210501T095830Z
RRULE:FREQ=WEEKLY;UNTIL=20210712T215959Z
SEQUENCE:1
SUMMARY:A1-1 Übung 
TRANSP:OPAQUE
UID:CA792CB8-2F3E-474B-B272-E357BD896C1C
CLASS:PUBLIC
END:VEVENT
END:VCALENDAR

A1-1 Übung 
2021-05-03 09:50`

**Comment by tobixen** [comment]
Then it's probably a bug in SOGo ... or maybe even a bug in the RFC itself, it's slightly ambiguous and different calendar servers seems to be doing different things ... or possibly it's me that have totally misunderstood the RFC.    Are you using the last version of SOGo by the way?  I do believe I got the unit tests passing in February towards SOGo.  Hm.  I did make some notes then ... it says that expand doesn't work, and a reference to https://www.sogo.nu/bugs/view.php?id=3065

**Comment by tobixen** [comment]
That means you should get back the original ical data for all recurring events that have any occurrences within the search parameters, because SOGo doesn't seem to support expand through the caldav protocol.  It does work through their web-ui though ...

**Comment by tobixen** [comment]
Closing this one, since it's a server problem.

Opening a new issue instead: improve support for broken servers.
