### ISSUE TITLE
'Calendar' object has no attribute '_handle_prop_response'

### ISSUE THREAD

**Issue by brainsky** [python-caldav/caldav#148]
when i use calendar.calendar_multiget(). it occur an error, 'Calendar' object has no attribute '_handle_prop_response'. like this: 
`  File "f:\caldav\caldav\examples\feishu.py", line 66, in <module>
    mul_events = feishu_calendars.calendar_multiget(event_urls=event_urls)
  File ".\caldav\objects.py", line 647, in calendar_multiget
    results = self._handle_prop_response(response=response, props=[dav.GetEtag()+cdav.CalendarData()])
AttributeError: 'Calendar' object has no attribute '_handle_prop_response`
I just clone master repo and copy basic_usage_examples.py to modify code. 
And I can‘t found which class has this method.

**Comment by tobixen** [comment]
Uff, that method is missing test code (#115), hence it broke after the last round of refactorings.

I believe the broken line can be replaced with this:

```python
        results = response.expand_simple_props([cdav.CalendarData()])
```

... but I don't have capacity to do any testing on this now.  Maybe you could do it?

Pull request is appreciated.

**Comment by brainsky** [comment]
Nice, Thanks!  I do this for me. It can solve my problems. it works!
`response.expand_simple_props()`
Thank you very much!
