### ISSUE TITLE
Redicale as caldav server

### ISSUE THREAD

**Issue by mohammadreza0852** [python-caldav/caldav#149]
Hi, I'm trying to use redicale as my own caldav server.
Does this library support redicale? If yes, does it need any specific configurations?
Thanks.

**Comment by tobixen** [comment]
Radicale should work by now.  One of the things the test suite does is spinning up a local radicale server.

Known caveats:

- While most caldav servers has a "default" calendar and returns 404 when someone tries to access a calendar that does not exist, radicale comes without any calendars, but creates one automatically when it's accessed. (this should not matter - but some of the example code fetches "the calendar" from the caldav server, this won't work out for a fresh radicale installation).
- freebusy is not supported yet, but it's on the long-term road map
- Expanding recurrent events is not yet supported, ref https://github.com/Kozea/Radicale/issues/662
- Calendar colors and calendar ordering is not supported (but this is also not defined by any RFC as far as I know - it's just some addons that Apple introduced at some point, and now is supported by multiple servers and clients).
- The scheduling RFC is not supported (as far as I know).  I don't have the reference, but if I remember right it was considered to be "outside the scope" for Radicale.

**Comment by mohammadreza0852** [comment]
Thanks for your answer.
I have created a calendar app using drf and react js and now I want to see my events on my mobile phone.
Do you think using caldav is the right choice?
Or is it better to write a mobile application and use my own APIs?

**Comment by tobixen** [comment]
Of course, I'd encourage you to use standards whenever possible.  The caldav standard may not be the easiest one to work with, but that's what we have.  By rolling your own you may end up spending time reinventing the wheel, and you may end up with a stand-alone app that cannot be easily integrated with other calendaring systems.

I was using davdroid, had some issues with it (it was draining battery, and I had to manually go into that app and sync the calendar), but while it was working I was accessing my home calendar server natively from the hauwei calendar app.  Now I have a new cell phone and haven't decided if I should install davdroid or do research into other adaptors.  Caldav support does not seem to come out of the box on android, unfortunately.

**Comment by mohammadreza0852** [comment]
Yes it needs a linker on android. Actually it was the reason i had doubt on using cal dav.
Thanks a lot.

**Comment by tobixen** [comment]
https://www.uk2.net/knowledgebase/display/UK2/How+To+Set+Up+CalDAV+Synchronization+For+Android says that davdroid is better than "Caldav Sync Free Beta".  I'm also a bit sceptical to apps that are "free" in google play (as they usually have another definition of "free" than what I do).
