### ISSUE TITLE
unable to get multiple attendees

### ISSUE THREAD

**Issue by toweih** [python-caldav/caldav#154]
Using v0.8 to read and parse a WebDav-calender I am able to get the first ContentLine of attendees, but no other.

Given the follwoing Event-object:
```
{'group': None, 
'behavior': <class 'vobject.icalendar.VEvent'>, 
'parentBehavior': <class 'vobject.icalendar.VCalendar2_0'>, 
'isNative': True, 
'contents': {
    'created': [<CREATED{}2021-10-16 21:51:21+00:00>], 
    'dtstamp': [<DTSTAMP{}2021-10-16 21:52:35+00:00>], 
    'last-modified': [<LAST-MODIFIED{}2021-10-16 21:52:35+00:00>], 
    'sequence': [<SEQUENCE{}2>], 
    'uid': [<UID{}9b6d51e3-5721-4ce3-8183-54166323809c>], 
    'dtstart': [<DTSTART{'X-VOBJ-ORIGINAL-TZID': ['Europe/Berlin']}2021-10-16 02:00:00+02:00>], 
    'dtend': [<DTEND{'X-VOBJ-ORIGINAL-TZID': ['Europe/Berlin']}2021-10-16 03:00:00+02:00>], 
    'status': [<STATUS{}CONFIRMED>], 
    'summary': [<SUMMARY{}Multi-Attendees 2>], 
    'attendee': [
        <ATTENDEE{'CN': ['joe'], 'CUTYPE': ['INDIVIDUAL'], 'PARTSTAT': ['NEEDS-ACTION'], 'ROLE': ['REQ-PARTICIPANT'], 'RSVP': ['TRUE']}mailto:joe@mail.org>, 
        <ATTENDEE{'CN': ['brad'], 'CUTYPE': ['INDIVIDUAL'], 'PARTSTAT': ['NEEDS-ACTION'], 'ROLE': ['REQ-PARTICIPANT'], 'RSVP': ['TRUE']}brad@mail.org>, 
        <ATTENDEE{'CN': ['julia'], 'CUTYPE': ['INDIVIDUAL'], 'PARTSTAT': ['NEEDS-ACTION'], 'ROLE': ['REQ-PARTICIPANT'], 'RSVP': ['TRUE']}mailto:julia@mail.org>, 
        <ATTENDEE{'CN': ['victoria'], 'CUTYPE': ['INDIVIDUAL'], 'PARTSTAT': ['NEEDS-ACTION'], 'ROLE': ['REQ-PARTICIPANT'], 'RSVP': ['TRUE']}mailto:victoria@mail.org>], 
    'organizer': [<ORGANIZER{'CN': ['Me']}mailto:me@mail.org>]}, 'name': 'VEVENT', 'useBegin': True}
```

I would expect the following to return a List of attendees: 
`    event.instance.vevent.attendee`
but it delivers the first ContentLine only.

Is there another way to do so?

**Comment by tobixen** [comment]
I don't remember how to deal with it in vobject - but I suggest checking the documentation there, http://eventable.github.io/vobject/ ... search for the string "If you want to access the full list of parameters", and perhaps what you're looking for is somewhere there.

There are quite many that seems to think that the icalendar library is better than the vobject library.  At some point in the future support for vobject in the caldav library may be deprecated.  I would recommend fetching the icalendar object through `event.icalendar_instance` and play with that one.

In any case, this is not a bug with the caldav library, so I'll mark the issue as closed. :-)

**Comment by toweih** [comment]
Works fine :) Thanks!
`
event.load()
data = event.icalendar_instance
for component in data.walk('vevent'):
    component.get('attendee')
    if type(attendees) == type([]):
        print "has multiple attendees!"
`
