### ISSUE TITLE
Unable to retrieve objects

### ISSUE THREAD

**Issue by Sigmun** [python-caldav/caldav#155]
I am trying to retrieve all objects of my calendar but it seems like I am not authorized to retrieve my calendars. I get the following error:
```
---------------------------------------------------------------------------
AuthorizationError                        Traceback (most recent call last)
/s1/xxx/ipykernel_209885/542434419.py in <module>
      6 cal_lyra = client.principal().calendar(name=cal_name)
      7 print(cal_lyra)
----> 8 lyra_events = cal_lyra.objects(load_objects=True)
      9 cal = Calendar()

/s1/xxx/conda/envs/scrapping/lib/python3.9/site-packages/caldav/objects.py in objects_by_sync_token(self, sync_token, load_objects)
   1019         props = dav.Prop() + dav.GetEtag()
   1020         root = cmd + [level, token, props]
-> 1021         (response, objects) = self._request_report_build_resultlist(root, props=[dav.GetEtag()], no_calendardata=True)
   1022         ## TODO: look more into this, I think sync_token should be directly available through response object
   1023         try:

/s1/xxx/conda/envs/scrapping/lib/python3.9/site-packages/caldav/objects.py in _request_report_build_resultlist(self, xml, comp_class, props, no_calendardata)
    722         else:
    723             props_ = [cdav.CalendarData()] + props
--> 724         response = self._query(xml, 1, 'report')
    725         results = response.expand_simple_props(props_)
    726         for r in results:

/s1/xxx/conda/envs/scrapping/lib/python3.9/site-packages/caldav/objects.py in _query(self, root, depth, query_method, url, expected_return_value)
    153         if url is None:
    154             url = self.url
--> 155         ret = getattr(self.client, query_method)(
    156             url, body, depth)
    157         if ret.status == 404:

/s1/xxx/conda/envs/scrapping/lib/python3.9/site-packages/caldav/davclient.py in report(self, url, query, depth)
    401          * DAVResponse
    402         """
--> 403         return self.request(url, "REPORT", query,
    404                             {'Depth': str(depth), "Content-Type":
    405                              "application/xml; charset=\"utf-8\""})

/s1/xxx/conda/envs/scrapping/lib/python3.9/site-packages/caldav/davclient.py in request(self, url, method, body, headers)
    521             except AttributeError:
    522                 ex.reason = "None given"
--> 523             raise ex
    524 
    525         # let's save the auth object and remove the user/pass information

AuthorizationError: AuthorizationError at 'https://xxxxxxx/dav/yyyy/Calendar/', reason 'Forbidden'
```
Of course, I have check my credentials and there are correct since I get the following error if I modify them:
```
AuthorizationError: AuthorizationError at 'https://xxxxxxx/dav/', reason 'invalid username/password'
```
These calendars are working under Thunderbird using caldav configuration.

I am working under Linux CentOS7, x86_64 and use python3.9  in a dedicated conda environment with caldav v0.8 installed with pip since it is not included in conda-forge.

**Comment by tobixen** [comment]
This looks like a compatibility issue.  What server do you use?

Some of the servers don't support the use of sync tokens, but I thought I had the proper workarounds for that in place

**Comment by tobixen** [comment]
(the issue contains lots of information about versions and environment on the client side, but nothing is said about the server side?)

**Comment by Sigmun** [comment]
I don't know have many informations on server side since it is a corporate server. What info do you need? And do you know how I can get these informations? (using thunderbird log perhaps?)

**Comment by tobixen** [comment]
I'm curious on what software the server is using, as I do have a list of "known issues" by server type - but I don't need it, it's more for my curiosity.

The server won't allow you to do take out sync-token reports for some reason or another.  Now I'd like you to try to take out other reports from the server ... like this:

```python
from datetime import date

events = cal_lyra.events()
todos =  cal_lyra.todos()
events_this_year = cal_lyra.date_search(start=date(2021, 1, 1), end=date(2022, 1, 1), expand=False)
events_this_year2 = cal_lyra.date_search(start=date(2021, 1, 1), end=date(2022, 1, 1), expand=True)
```

(at the moment I don't remember if date_search accepts date objects ... perhaps it needs to be datetime ... hm)

**Comment by Sigmun** [comment]
this code is 100% functional.

**Comment by tobixen** [comment]
Ok, is this an acceptable workaround as for now?

**Comment by Sigmun** [comment]
Unfortunately, I've got the same behaviour on the `add_event` command:
```python
# getting event from icalendar
cal = Calendar()
# filling it
# ....
# export to caldav
for e in cal.subcomponents:
    cal_lyra.add_event(e.to_ical())
```
gives me the following:
```
---------------------------------------------------------------------------
AuthorizationError                        Traceback (most recent call last)
myCalDav.py in <module>
      7                 continue
      8     print(e.to_ical())
----> 9     cal_lyra.add_event(e.to_ical())

/tmp_user/conda/envs/39/lib/python3.9/site-packages/caldav/objects.py in save_event(self, ical, no_overwrite, no_create)
    586         """
    587         e = Event(self.client, data=ical, parent=self)
--> 588         e.save(no_overwrite=no_overwrite, no_create=no_create, obj_type='event')
    589         return e
    590 

/tmp_user/conda/envs/39/lib/python3.9/site-packages/caldav/objects.py in save(self, no_overwrite, no_create, obj_type, if_schedule_tag_match)
   1462         ## try-send-data-except-wash-through-vobject-logic here.
   1463         try:
-> 1464             self._create(self.data, self.id, path)
   1465         except error.PutError:
   1466             self._create(self.vobject_instance.serialize(), self.id, path)

/tmp_user/conda/envs/39/lib/python3.9/site-packages/caldav/objects.py in _create(self, data, id, path)
   1366             path = quote(id) + ".ics"
   1367         path = self.parent.url.join(path)
-> 1368         r = self.client.put(path, data,
   1369                             {"Content-Type": 'text/calendar; charset="utf-8"'})
   1370 

/tmp_user/conda/envs/39/lib/python3.9/site-packages/caldav/davclient.py in put(self, url, body, headers)
    446         Send a put request.
    447         """
--> 448         return self.request(url, "PUT", body, headers)
    449 
    450     def post(self, url, body, headers={}):

/tmp_userconda/envs/39/lib/python3.9/site-packages/caldav/davclient.py in request(self, url, method, body, headers)
    521             except AttributeError:
    522                 ex.reason = "None given"
--> 523             raise ex
    524 
    525         # let's save the auth object and remove the user/pass information

AuthorizationError: AuthorizationError at 'https://xxxxxx/dav/username/calendar/bf21b4a3-4ed1-11ec-9708-989096a70c38.ics', reason 'Forbidden'
```

Is it due to the same error behind? This gonna be more problematic since my goal is to keep my caldav synced with another external calendar in Read-Only mode.

**Comment by tobixen** [comment]
What happens if you try to do a simple GET towards `https://xxxxxx/dav/username/calendar/bf21b4a3-4ed1-11ec-9708-989096a70c38.ics`?  (i.e. by pasting the URL into your browser?)

**Comment by Sigmun** [comment]
Using firefox, I get the valid ics file.

**Comment by Sigmun** [comment]
I am also able to put an event with `curl -T myevent.ics https://xxxxxx/dav/username/calendar/`so the problem seems to be definitively from the caldav plugin, right?

**Comment by tobixen** [comment]
Then ... indeed.  Things would be easier if I could have a login and try to interact with your server from my side.

Also, please verify that things are still broken when using the fresh 0.8.1-release.

**Comment by Sigmun** [comment]
Ok, this stay the same with fresh new 0.8.1 version:
```
---------------------------------------------------------------------------
AuthorizationError                        Traceback (most recent call last)
/ipykernel_11345/4109012102.py in <module>
      8     print(e)
      9     print(e.to_ical())
---> 10     cal_lyra.add_event(e.to_ical())

/conda/envs/39/lib/python3.9/site-packages/caldav/objects.py in save_event(self, ical, no_overwrite, no_create)
    602         """
    603         e = Event(self.client, data=ical, parent=self)
--> 604         e.save(no_overwrite=no_overwrite, no_create=no_create, obj_type='event')
    605         return e
    606 

/conda/envs/39/lib/python3.9/site-packages/caldav/objects.py in save(self, no_overwrite, no_create, obj_type, if_schedule_tag_match)
   1499         ## try-send-data-except-wash-through-vobject-logic here.
   1500         try:
-> 1501             self._create(self.data, self.id, path)
   1502         except error.PutError:
   1503             self._create(self.vobject_instance.serialize(), self.id, path)

/conda/envs/39/lib/python3.9/site-packages/caldav/objects.py in _create(self, data, id, path)
   1391         path = self.parent.url.join(path)
   1392         ## SECURITY TODO: we should probably have a check here to verify that no such object exists already
-> 1393         r = self.client.put(path, data,
   1394                             {"Content-Type": 'text/calendar; charset="utf-8"'})
   1395 

/conda/envs/39/lib/python3.9/site-packages/caldav/davclient.py in put(self, url, body, headers)
    470         Send a put request.
    471         """
--> 472         return self.request(url, "PUT", body, headers)
    473 
    474     def post(self, url, body, headers={}):

/conda/envs/39/lib/python3.9/site-packages/caldav/davclient.py in request(self, url, method, body, headers)
    547             except AttributeError:
    548                 ex.reason = "None given"
--> 549             raise ex
    550 
    551         # let's save the auth object and remove the user/pass information

AuthorizationError: AuthorizationError at 'https://xxxxxx/dav/username/calendar/b4b9a992-50fd-11ec-9418-989096a70c38.ics', reason 'Forbidden'
```
Does the problem could com from the fact that the given url already includes the ics filename? Using curl, I only put the ics file in the calendar url.

**Comment by Sigmun** [comment]
> Does the problem could com from the fact that the given url already includes the ics filename? Using curl, I only put the ics file in the calendar url.

It is not the problem, I am able to put an ics file with its filename in the url using curl

**Comment by tobixen** [comment]
according to REST standards, one should POST to a collection and PUT to a file.  DAV is not REST, but still ... I don't think one is supposed to PUT something directly to the calendar (even if it works with NextCloud it may break towards other servers).  Or perhaps I should read the RFC once more :-)

**Comment by Sigmun** [comment]
However, I've tried to modify caldav/objects.py to put the event with only `self.parent.url` as path (line 1393) and add debug output:
```python
         path = self.parent.url.join(path)
        print("DEBUG:path:", path)
        ## SECURITY TODO: we should probably have a check here to verify that no such object exists already
        r = self.client.put(self.parent.url, data,
                            {"Content-Type": 'text/calendar; charset="utf-8"'})
        print("DEBUG:status:",r.status)
```
In that case, thanks to a print command I put before the put command, I can see this output:
```
DEBUG:path: https://xxxxx/dav/username/calendar/4faaecf5-5104-11ec-b1ed-989096a70c38.ics
DEBUG:status: 406
DEBUG:path: https://xxxxx/dav/username/calendar/4faaecf5-5104-11ec-b1ed-989096a70c38.ics
DEBUG:status: 406

---------------------------------------------------------------------------
PutError                                  Traceback (most recent call last)
/conda/envs/39/lib/python3.9/site-packages/caldav/objects.py in save(self, no_overwrite, no_create, obj_type, if_schedule_tag_match)
   1501         try:
-> 1502             self._create(self.data, self.id, path)
   1503         except error.PutError:

/conda/envs/39/lib/python3.9/site-packages/caldav/objects.py in _create(self, data, id, path)
   1399         elif not (r.status in (204, 201)):
-> 1400             raise error.PutError(errmsg(r))
   1401 

PutError: 406 Not Acceptable

b''

During handling of the above exception, another exception occurred:

PutError                                  Traceback (most recent call last)
/ipykernel_18394/2119939230.py in <module>
      9     print(e)
     10     print(e.to_ical())
---> 11     cal_lyra.add_event(e.to_ical())

/conda/envs/39/lib/python3.9/site-packages/caldav/objects.py in save_event(self, ical, no_overwrite, no_create)
    602         """
    603         e = Event(self.client, data=ical, parent=self)
--> 604         e.save(no_overwrite=no_overwrite, no_create=no_create, obj_type='event')
    605         return e
    606 

/conda/envs/39/lib/python3.9/site-packages/caldav/objects.py in save(self, no_overwrite, no_create, obj_type, if_schedule_tag_match)
   1502             self._create(self.data, self.id, path)
   1503         except error.PutError:
-> 1504             self._create(self.vobject_instance.serialize(), self.id, path)
   1505         return self
   1506 

/conda/envs/39/lib/python3.9/site-packages/caldav/objects.py in _create(self, data, id, path)
   1398             path = [x[1] for x in r.headers if x[0] == 'location'][0]
   1399         elif not (r.status in (204, 201)):
-> 1400             raise error.PutError(errmsg(r))
   1401 
   1402         self.url = URL.objectify(path)

PutError: 406 Not Acceptable

b''
```
Any idea of new tests I can run?

**Comment by tobixen** [comment]
So you say you can PUT using curl, but not through the caldav library?  Please double check that it's exactly the same URL and exactly the same ical data.

**Comment by tobixen** [comment]
If it works with curl but not with the caldav library and the URL and the ical data is exactly the same, then there must be a problem with the headers.

**Comment by Sigmun** [comment]
Indeed, after that check, it is working with `curl "https://xxxxx/dav/username/calendar/newevent.ics" -T newevent.ics`
 but not with caldav:
```python
client = caldav.DAVClient(**data)
cal = client.principal().calendar(name=cal_name)
with open("newevent.ics", "r") as f:
    e = Event.from_ical("".join(f.readlines())).subcomponents[0]
cal.add_event(e)
```

**Comment by Sigmun** [comment]
I've managed to put the event on the caldav server using directly reuqests plugin:
```python
with open('newevent.ics') as f:
     lines = f.readlines()
requests.put("https://xxxxxx/dav/username/calendar/newevent.ics", data="".join(lines), auth=auth)
```

**Comment by tobixen** [comment]
Can you test the workaround described in #158 ?

(or you may wait until I've released 0.8.2 ... though, I don't know if I will release it today or next month)

**Comment by tobixen** [comment]
There!  Please test if release 0.8.2 solves the problems with this caldav server as well.  I'm a bit optimistic on this one, one of the differences between the manual PUT and the PUT through the caldav library may be the auth object class.

**Comment by Sigmun** [comment]
Still the same with 0.8.2, with `auth` or `username` and `password` kwarg in the DAVClient arguments

**Comment by tobixen** [comment]
So you say that you can PUT just fine by feeding the requests library with basically the same as the caldav library is sending, but when doing it through the caldav library you get 406-errors.

At this point it's a good idea to use the python debugger.  What I would do to debug this issue is to throw in the line `import pdb; pdb.set_trace()` in In `davclient.py`, `request`-method, just before the call to the requests library - in v0.8.2, that is on line 588.

Do you know how to use the debugger?  If not, then read on:

Assuming you run your python code from the terminal (and without redirecting stdout to a log file or something like that), this will cause the pdb prompt to appear just before the HTTP-request is sent to the server, and from there it's possible to enter python commands (or press "c" to continue execution).  (Be aware that the dbg commands takes precedence - if you try to enter things like `r.reason`, it will assume you meant the pdb-command `r` - you may work around this by doing a `response=r` or by writing `print(r.reason)`, etc).

If there are tons of successful requests done before the broken one, I suggest putting `pdb.set_trace()` into an `if`-block.  Something like this:

```python
if method == 'PUT':
    import pdb; pdb.set_trace()
```

Now the next statement can be rewritten like this:

```
response = self.session.request(method, url, data=to_wire(body), headers=combined_headers, auth=auth)
```

Try to enter that into the debugger, and check `response.status` or `response.reason`.  You are supposed to still get 406.

Now you have said that you have successfully used the request library for saving an event.  Try playing with the statement above.  Perhaps it will pass if you bypass the session object?

```
response = requests.request(method, url, data=body, headers=combined_headers, auth=auth)
```

Perhaps if you change the headers or auth?  Perhaps the problem is in the usage of `"\r\n"` vs `"\n"` in the body?

I would be very happy to learn the results here.

**Comment by Sigmun** [comment]
ok I'll try. But I face a first problem before trying it. If I put an event I grab from the calendar before, it works using requests.put but if I create an event from the icalendar. Event class, I cannot put it. I think this is because the uid an other things you do in the Object._create function. Have you an idea of how to get a ready-to-put Event in the python session?

**Comment by tobixen** [comment]
At the line quoted, `body` is a bytestring object, you may replace it or edit it as you like.  Perhaps the issue here is the linebreaks.

An `Event`-object is just a simple wrapper over icalendar data.  The constructor takes too many parameters indeed and it's too poorly documented ... I should clean up the API properly in v1.0. Those things are relevant to pass when constructing the object:

* `parent` should typically be set to a `Calendar`-object
* `url` - the full URL - if not given, a URL will be constructed based on the id and parent.url.
* `data` - the ical data.  A string or a bytestring is acceptable.  I don't remember, but I think I've also made support for vobject and icalendar object to be passed.

**Comment by tobixen** [comment]
`Object._create` is also something I'm unhappy with, it will definitively not survive in it's present form in version 1.0 of the library.

**Comment by tobixen** [comment]
(and the last commit did indeed introduce more redundant code ... I'm currently doing work to clean up `davclient.requests` in the master branch)

**Comment by Sigmun** [comment]
here are the returns of my debug test:
```python
> /conda/envs/39/lib/python3.9/site-packages/caldav/davclient.py(589)request()
-> r = self.session.request(
(Pdb) response = self.session.request(method, url, data=to_wire(body), headers=combined_headers, auth=auth)
(Pdb) response.status
*** AttributeError: 'Response' object has no attribute 'status'
(Pdb) response.reason
'Forbidden'
(Pdb) response = requests.request(method, url, data=body, headers=combined_headers, auth=auth)
(Pdb) response.reason
'Forbidden'
(Pdb) 
```

**Comment by tobixen** [comment]
`status_code`, not status.

**Comment by tobixen** [comment]
So, removing the session did not help.  Next step would be to replace `body` with some known valid ICS

**Comment by Sigmun** [comment]
This is it. The problem comes from the body content. 
I was trying to save individual event by looping over a list of calendar `subcomponents` in order to make test on them. 
```python
for e in cal.subcomponents:
    if test==True:
        cal_lyra.add_event(e.to_ical())
```

But it appears that `calendar.save_event` is expecting `VCALENDAR` data and not `VEVENT` data, even if I am saving them in a single ics file in the caldav calendar. 
So my guess is that maybe the `Event` class you are not 100% confident with gonna be useful!

**Comment by tobixen** [comment]
I was just writing up more suggestions on how to debug, but nevermind that then :-)

So what you are saying is that the `body` does not contain `BEGIN:VCALENDAR`, but should contain it?  Or the opposite?

**Comment by Sigmun** [comment]
I don't know the RFC so I cannot tell you what the body should contain. But in my opinion, If you offer the `calendar.save_event` method, it should at least allow you to give an event as attribute, not necessarily a calendar. Maybe `save_event` should allow the user to give an `Event` instance also, not just ical string.

Nevertheless, the server doesn't seem to allow to `PUT` some `VEVENT` individually.

**Comment by tobixen** [comment]
Oh.  Could you try the master branch of the caldav library?  I was incidentally writing up some code in the weekend that may solve this problem.

**Comment by tobixen** [comment]
No, the current master will not solve this issue.  But wait ten minutes and probably it will ... :-)

**Comment by Sigmun** [comment]
Ok, the problem was coming from the absence of `uid` in the Event

**Comment by tobixen** [comment]
Oh.  I thought I had that covered already.  I'll check again.

**Comment by tobixen** [comment]
Apparently there is no water-tight logic as of now to ensure the uid field is set.  Actually I even found this in the test code:

```
        # adding a todo without an UID, it should also work
        if not self.check_compatibility_flag('uid_required'):
            c.save_todo(todo7)
 ```

However, the `_create` logic is able to create an uid.

I'll create a new ticket for refactoring the _create logic, and make sure there will always be an uid set when saving things to the database.

**Comment by Sigmun** [comment]
Ok, so far, if I am adding an `uid` to the event and put only this event in a `icalendar.Calendar`, I can make `cal.save_event` working.  
```python
for e in cal.subcomponents:
    if test==True:
        e.add('uid', uid)
        caldata = Calendar()
        caldata.add_component(e)
        cal_lyra.add_event(caldata.to_ical())
```

For me, the `save_event` should allow the furniture of a `VEVENT`, but also of a `icalendar.Event` and with or without `uid`.

Although, I still have the initial problem with `cal.objects(load_objects=True)` not working, but the workaround `cal.events()` is working.

**Comment by tobixen** [comment]
With the master branch it's all easier, it's possible to add events without generating the icalendar data.

```python
my_event = my_new_calendar.save_event(
    dtstart=datetime(2020,5,17,8),
    dtend=datetime(2020,5,18,1),
    summary="Do the needful",
    rrule={'FREQ': 'YEARLY'})
```
