### ISSUE TITLE
RFC: extend the scope of the caldav library?

### ISSUE THREAD

**Issue by tobixen** [python-caldav/caldav#156]
The scope of the caldav library has basically been to push icalendar data to and from a caldav server, without doing anything on the icalendar level.  There has been some "creep", notably:

* The library is "ironing out" broken icalendar from servers not supporting the standards well enough
* It has "always" been possible to take out an instantiated object (vobject) by doing `event.instance`, newer releases also supports the competing icalendar library through `event.icalendar_instance`
* Tasks can be completed by doing a `todo.complete()`.  This involved modifying the icalendar data before sending it to the server.
* The RFC6638-support (a bit of work in progress - undertested functionality) adds things like `event.accept_invite()` which requires some action on the icalendar level.

Now I'm considering to expand the scope a bit further and let it do things like creating simple icalendar data, or search a calendar for all tasks with a specific category - for instance, I'm considering allowing a new event to be put in like this:

```python
calendar.add_event(
    dtstart=datetime(2023, 10, 1, 15, 33), 
    dtend=dtstart+datetime.timedelta(hours=5), 
    summary="testevent")
```

The background is that I'm also maintaining/developing [calendar-cli](https://github.com/tobixen/calendar-cli/).  It allows things like creating events and tasks, viewing the agenda, completing tasks etc from the command line.  I'm intending to refactor it a lot in an upcoming release.  There is some extra logic in calendar-cli compared to the caldav library, as the calendar-cli allows an end-user to operate the calendar without any knowledge of icalendar, like doing `calendar-cli  calendar add 2023-10-01T15:33+5h testevent`.  I would like the cli to be a thin wrapper over a library, so I can see two options ... create a new calendaring library with the extra functionality needed, or move the functionality to caldav. 

Any opinions?

**Comment by tobixen** [comment]
@cyrilrbt , do you have any thoughts? :-)

**Comment by cyrilrbt** [comment]
Sounds like it could be helpful, and maybe even simplify how the library is used eventually. Go for it :)
