### ISSUE TITLE
After update verify_login raises AuthorizationError because of changed default "method" parameter

### ISSUE THREAD

**Issue by rstemmer** [python-caldav/caldav#161]
Hi

I just updated my server and suddenly one of my python scripts stopped working.
It always crashed when trying the `principal` method.

## Environment

Before the update: Python 3.9, caldav 0.8.0
After the update: Python 3.10, caldav 0.8.2
Server: Nextcloud 22.2.3

```python
self.davclient = caldav.DAVClient(
    url = "https://…/remote.php/dav/calendars/",
    username = "username",
    password = "1234",
   ssl_verify_cert = False) # Self Signed

principal = self.davclient.principal()
```

## Exception

```python
  File "/…/calendarclient.py", line 175, in Connect
    principal       = self.davclient.principal()
  File "/usr/lib/python3.10/site-packages/caldav/davclient.py", line 350, in principal
    self._principal = Principal(client=self, *largs, **kwargs)
  File "/usr/lib/python3.10/site-packages/caldav/objects.py", line 399, in __init__
    cup = self.get_property(dav.CurrentUserPrincipal())
  File "/usr/lib/python3.10/site-packages/caldav/objects.py", line 174, in get_property
    foo = self.get_properties([prop], **passthrough)
  File "/usr/lib/python3.10/site-packages/caldav/objects.py", line 197, in get_properties
    response = self._query_properties(props, depth)
  File "/usr/lib/python3.10/site-packages/caldav/objects.py", line 141, in _query_properties
    return self._query(root, depth)
  File "/usr/lib/python3.10/site-packages/caldav/objects.py", line 159, in _query
    ret = getattr(self.client, query_method)(
  File "/usr/lib/python3.10/site-packages/caldav/davclient.py", line 398, in propfind
    return self.request(url or self.url, "PROPFIND", props,
  File "/usr/lib/python3.10/site-packages/caldav/davclient.py", line 585, in request
    self.verify_login()
  File "/usr/lib/python3.10/site-packages/caldav/davclient.py", line 568, in verify_login
    raise error.AuthorizationError(url=url, reason=resp.reason)
caldav.lib.error.AuthorizationError: AuthorizationError at 'https://…/remote.php/dav/calendars/', reason 'Method Not Allowed'
```
## Debugging

I figured out that there were lots of changes in the davclient.py file of the packaged, so I stated my hunt for the issue there - and found it there :)

**Old Code:** davclient.py Line 465:
```python
def request(self, url, method="GET", body="", headers={}):
```

**New Code:** davclient.py Line 505
```python
def verify_login(self, url=None, method="PROPFIND", body="", headers={}):
```

**The Issue:** The default method changed from `"Get"` in 0.8.0 to `"PROPFIND"` on 0.8.2

**Fix:** I replaced the method.
```python
def verify_login(self, url=None, method="GET", body="", headers={}):
```

## Thoughts

I'v no idea if this is an issue with your code or my Nextcloud setup.
For now I solved the issue by editing the code in site-packaged.
If it is not a bug it would be nice to make the default method some kind of configurable.

Kind regards,
Ralf

**Comment by tobixen** [comment]
The `verify_login` will be removed completely in 0.9.  Please test the master and see if that solves the issue.  Too bad that 0.8.2 is broken for you :-(

**Comment by tobixen** [comment]
I'm considering to change PROPFIND to GET as suggested and release a 0.8.3 - but it will probably break radicale, which only require credentials for a PROPFIND to find the logged in principal, so that probably means even more work ... which of course doesn't feel much rewarding, given that the code to be fixed is already deleted in the master branch.

In any case, it's important for me to know if the master branch (and upcoming v0.9)  works with your server or not.

**Comment by rstemmer** [comment]
I installed 0.9.0.dev0 from the master branch.
Works for me without any issues.

Thank you very much.

**Comment by tobixen** [comment]
Great, thanks for the information.  Maybe I'll skip working more on the 0.8-branch to release 0.9 soon instead of tweaking on this.  Closing this issue as for now.
