### ISSUE TITLE
Docs already reference/ use caldav v0.9, but not released yet

### ISSUE THREAD

**Issue by flashbyte** [python-caldav/caldav#162]
Hi, I'm new to your library and struggled for some time to go trough the basic example, because its using v0.9, which isn't released yet. For beginners this is a bit puzzling.
Could you role back the doc changes, if v0.9 release isn't close?
  best regards

**Comment by tobixen** [comment]
Known issue.  The service at readthedocs will push out new doc on every commit to master.  The master is tracking an upcoming 0.9 release.  I probably should create a "latest_release"-branch or something like that, and let readthedocs track that branch.  At the other hand, if I do some minor fixups on the documentation, I would like to publish it immediately and without making a new release containing nothing but minor fixups on the documentation.

I'm not sure what is best to do ... except, maybe release 0.9 soon? :-)

I'd like to have a stab at issue #16 before releasing 0.9.

**Comment by flashbyte** [comment]
Maybe just have a docs branch, which readthedocs tracks.
And on release you merge it in to master.

THX for the response.

**Comment by tobixen** [comment]
A docs branch would probably make sense.  If I would only remember to keep it up to date.  I'll leave this issue open for a while and consider it before starting with a v0.10 or v1.0.

The major new thing with v0.9 (and I did some efforts updating the doc as well if I remember ) is that it's possible to create new events (and tasks and journals) without sending ical data to the library.  Hence this (as documented) doesn't work with version 0.8:

```python
  my_event = my_new_calendar.save_event(
      dtstart=datetime.datetime(2020,5,17,8),
      dtend=datetime.datetime(2020,5,18,1),
      summary="Do the needful",
      rrule={'FREQ': 'YEARLY'))
```
