### ISSUE TITLE
Regression: Wrong credentials result in "AttributeError: 'DAVClient' object has no attribute 'password'"

### ISSUE THREAD

**Issue by BjoKaSH** [python-caldav/caldav#164]
This is on the "master" branch.
If the ```DAVClient```  constructor is called with wrong credentials, then a subsequent call to ```principal()``` results in an attribute error ```AttributeError: 'DAVClient' object has no attribute 'password'```  in line https://github.com/python-caldav/caldav/blob/cbca28592a4ccbf9f06601fdbbf2656e4afff17f/caldav/davclient.py#L536

Test case:
```python
import caldav

client =  caldav.DAVClient("https://example.com/some/path", username="some_user", password="some_secret")
user_principal = client.principal()
 ```
This was introduce by commit 164f88d8 and is caused by lines https://github.com/python-caldav/caldav/blob/cbca28592a4ccbf9f06601fdbbf2656e4afff17f/caldav/davclient.py#L548-L549 which should read instead:
```python
            self.username = None
            self.password = None
```

I found this while debugging another authorization problem for which a PR is coming soon and will fix this too, plus the other problem I was actually investigating.

**Comment by tobixen** [comment]
Sorry the slow response ... I've been knocked out by a booster vaccine shot today (I do wonder a bit if the booster shot really helps against Omikron or if the push to give everyone booster doses is just some panic kneejerk reaction by the government ... I would not take it if I had known it would knock me out for a full day ... but I digress).

The suggestion to set it to None seems good.

**Comment by BjoKaSH** [comment]
Don't worry, I sometimes have much longer response times - even without Corona vaccination. (Got my third today, let's see how tomorrow will workout ...)
