### ISSUE TITLE
Digest authentication fails with some (really old) servers

### ISSUE THREAD

**Issue by BjoKaSH** [python-caldav/caldav#165]
Commit 13a4714 introduced proper handling for multi-lingual characters.  Unfortunately this breaks authentication with some really old pre-UTF8 servers, For example servers based on SabreDAV 3.1.x

See  PR #166 and #167 for a proposed solution.

**Comment by tobixen** [comment]
I was indeed wondering a bit about that - the fix did solve my immediate problems, but it's not obvious all servers would expect the password in UTF8.
