### ISSUE TITLE
"Path expected in response"

### ISSUE THREAD

**Issue by JeeCee1** [python-caldav/caldav#168]
Hi, 
I'm getting this warning in Home Assistant:

````
 Logger: caldav
Source: /usr/local/lib/python3.9/site-packages/caldav/objects.py:232
First occurred: 8:33:30 AM (1 occurrences)
Last logged: 8:33:30 AM
Bypassing a known iCloud bug - path expected in response: /1345102631/principal/, path found: /principal/ ... Please raise an issue at https://github.com/python-caldav/caldav/issues or reach out to t-caldav@tobixen.no, include this error and the traceback and tell what server you are using
````
I'm using this server: `https://caldav.icloud.com`

<html><body>

Version | core-2022.2.0
-- | --
Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.7

</body>
</html>

**Comment by tobixen** [comment]
What calendar server do you use?

**Comment by tobixen** [comment]
iCloud?

**Comment by tobixen** [comment]
Is this something new after upgrading to home assistant 2022.2, or has it always been there?  (hm ... I think one of the new features in home assistant 2022.2 was "more debug logging", so that may be a red herring)

**Comment by JeeCee1** [comment]
Hi,m I use this calendar: https://caldav.icloud.com

Well, I was doing some housekeeping and resolving my many errors which have crept up over the last releases of HA Core. It might have been there for a while already, but I did just upgrade this morning to the latest version.
Remote syslog is still ToDo, o I cann't look back.

**Comment by tobixen** [comment]
Thanks for reporting.  I'll simply remove that log line for the next release of the caldav library.
