### ISSUE TITLE
Deviation from expectations found

### ISSUE THREAD

**Issue by martijnvandijk** [python-caldav/caldav#169]
I'm using home assistant and found the following in my logs after the latest update of this library:

```
Deviation from expectations found. Please raise an issue at https://github.com/python-caldav/caldav/issues or reach out to t-caldav@tobixen.no, include this error and the traceback and tell what server you are using

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/caldav/lib/error.py", line 25, in assert_
    assert(condition)
AssertionError
```

Related error with more elaborate stacktrace:

```
Logger: homeassistant.components.calendar
Source: components/caldav/calendar.py:87
Integration: Calendar (documentation, issues)
First occurred: 8:37:42 PM (1 occurrences)
Last logged: 8:37:42 PM
Error while setting up caldav platform for calendar

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/caldav/calendar.py", line 87, in setup_platform
    calendars = client.principal().calendars()
  File "/usr/local/lib/python3.9/site-packages/caldav/objects.py", line 474, in calendars
    return self.calendar_home_set.calendars()
  File "/usr/local/lib/python3.9/site-packages/caldav/objects.py", line 441, in calendar_home_set
    if '@' in calendar_home_set_url and not '://' in calendar_home_set_url:
TypeError: argument of type 'NoneType' is not iterable
```

I'm using Nextcloud 22 for the calendar URL. This is the URL I used before: `https://next.wolck.net/remote.php/dav/public-calendars/iknPF5PRwQy8QzPR/?export`. It is no longer active but I'm willing to set up a test calendar to help you test this.

**Comment by martijnvandijk** [comment]
For the record, I also opened an issue with the home assistant project: https://github.com/home-assistant/core/issues/65941

**Comment by martijnvandijk** [comment]
Further information: home assistant uses version 0.8.2.

**Comment by tobixen** [comment]
So apparently `self.get_property(cdav.CalendarHomeSet())` returns None, while the code expect it to return a string.  Making some workaround probably won't help, then it probably won't load any calendars at all.

Did this work in earlier versions of the caldav library?

Accessing a test-calendar with this issue would help me a lot to pinpoint it.

I will hopefully find some time for bughunting this week.  It would be great if I could push out a 0.9.0-version this week and if it could be included in the next HA version, but I cannot commit myself to any promises wrg of a timeline.

**Comment by tobixen** [comment]
It would be nice if you could test the master branch of the caldav library, eventually.  I had someone else with NextCloud reporting that 0.8.2 broke their integration, while the master branch logic works (the breakage was with authentication, not with the calendar home set ... but then again, perhaps it's an authorization issue causing the get_property function to return None?)

**Comment by martijnvandijk** [comment]
It worked fine in the previous release of home assistant, which used an older version of the library. 

Here's the test link. I confirmed it to cause the same issue.

https://next.wolck.net/remote.php/dav/public-calendars/zcmNxEByC7nWygoP?export

As far as your remark about authentication goes: I don't think that's the case here. I set this link up without any authentication.

**Comment by tobixen** [comment]
That link is an ics feed, it's not a caldav link ... perhaps that's the issue?

**Comment by tobixen** [comment]
Try to set the URL to `https://next.wolck.net/remote.php/dav/` and see if that changes anything?

**Comment by martijnvandijk** [comment]
@tobixen thanks for pointing out my mistake. That works after setting up the password! The events show up fine now.

Makes me wonder how it worked in the first place...
