### ISSUE TITLE
Write to body of event

### ISSUE THREAD

**Issue by myzinsky** [python-caldav/caldav#170]
There is the save_event function that has dstart dtend and summary. However how can I set the HTML body of an event?

**Comment by myzinsky** [comment]
```python
        event = nc.save_event(
            dtstart=item.start,
            dtend=item.end,
            summary=item.subject,
        )

        event.icalendar_instance.subcomponents[0]['description'] = item.body
        event.save()
        
```

does the job for me

**Comment by tobixen** [comment]
With the master branch, it should be possible to do ...

```
event = nc.save_event(
            dtstart=item.start,
            dtend=item.end,
            summary=item.subject,
            description = item.body
        )
```

... but I think the description should be regular text and not html according to the standards.  Some calendar clients may probably show the event correctly if HTML is given.

**Comment by myzinsky** [comment]
@tobixen thanks for the clarification. 

I read that X-ALT-DESC;FMTTYPE=text/html should be set instead. However, it seems to be ignored by my clients.... hm any idea?

**Comment by tobixen** [comment]
Then you'll have to choose between supporting your clients or comply with the standards :-)

Anyway, headers starting with X is not a part of the official standards.

If you do choose to put HTML into the description, you should consider that some clients will display it as plain text, so it may be an idea to write the HTML in such a way that it can be read by humans.

(But I'm not an expert on the ical format ... I'm sure there are plenty of other people that has more qualified opinions than me on how to add html descriptions to calendar events)
