### ISSUE TITLE
Old pypi version

### ISSUE THREAD

**Issue by TheMcs000** [python-caldav/caldav#177]
The [pypi version](https://pypi.org/project/caldav/) linked in the README.md is very old and the example linked in the docs and readme don't work anymore.

I just downloaded the version from the github and can work with it locally. So it is not urgent for me.  
However, I would still suggest to update the pypi version for other developers.

**Comment by tobixen** [comment]
Version 0.9 hasn't been released yet, it's long overdue, I was going to release it in late February, but then a war broke out :-(

**Comment by tobixen** [comment]
I'm planning to release v0.9 by tomorrow, that should solve this issue.
