### ISSUE TITLE
date_search fails on Baikal 0.4.5 and 0.4.6

### ISSUE THREAD

**Issue by ghost** [python-caldav/caldav#18]
This server from test.py works: http://baikal.tobixen.no
It is reportedly the "older" Baikal, but I don't know what version it's running.

This server from test.py is not reachable: http://baikal-test.caldav-servers.tobixen.no

On recent (0.4.5 and 0.4.6) versions of Baikal, date_search(datetime)     works (with only one argument), but date_search(datetime(), datetime())    with two arguments generates an internal server error (500).

Considering that functions properly on older Baikal servers, this does not appear to be a regression in python-caldav but rather something broken by updates to Baikal. I have not tried this against raw sabre/dav.

**Comment by tobixen** [comment]
I'm sorry that the test framework I set up isn't maintained.

I'd say that "500 internal server error" indicates a problem at the server side ... though, eventually it could be a protocol problem and "just" bad error handling on the server side.

Unfortunately I don't have time looking more into it right now.  I will try to get the test framework back up and running at some point, I'll check out the versioning issue then.

**Comment by tobixen** [comment]
I've rolled out the latest baikal now, at a new URL, will try to iron out any issues during this weekend.

Sorry the late response

**Comment by tobixen** [comment]
All tests passes on the latest baikal server version with the latest code in the dev branch.  Closing this as for now, feel free to reopen if you can reproduce any problems.
