### ISSUE TITLE
TextMatch Filter not work

### ISSUE THREAD

**Issue by andriy-sa** [python-caldav/caldav#19]
` all = []
        data = cdav.CalendarData()
        prop = dav.Prop() + data

        filter = \
            cdav.Filter().append(
                cdav.CompFilter("VCALENDAR").append(
                    cdav.CompFilter("VEVENT").append(
                        cdav.PropFilter("SUMMARY").append(
                            [cdav.TextMatch("Holiday", negate=True)]))))

        root = cdav.CalendarQuery() + [prop, filter]
        
        response = self._query(root, 1, query_method='report')
        results = self._handle_prop_response(
            response, props=[cdav.CalendarData()])
        for r in results:
            all.append(Event(
                self.client, url=self.url.join(r),
                data=results[r][cdav.CalendarData.tag], parent=self))

        return all`

XML:
<?xml version='1.0' encoding='utf-8'?>
<C:calendar-query xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:D="DAV">
  <ns0:prop xmlns:ns0="DAV:">
    <C:calendar-data/>
  </ns0:prop>
  <C:filter>
    <C:comp-filter name="VCALENDAR">
      <C:comp-filter name="VEVENT">
        <C:prop-filter name="SUMMARY">
          <C:text-match negate-condition="yes" collation="i;octet">Holiday</C:text-match>
        </C:prop-filter>
      </C:comp-filter>
    </C:comp-filter>
  </C:filter>
</C:calendar-query>

Google Calendar CalDav

**It always return all events.**

**Comment by tobixen** [comment]
As far as I understand, this XML should return all events not having the summary set to "Holiday".  If it also return the Holiday-event, I believe there is something wrong at the server side.  A workaround can be to filter them out at the client side.

Maybe you meant not to have the negate flag?

Or do I misunderstand something?

**Comment by tobixen** [comment]
Closing this due to lack of feedback.
