### ISSUE TITLE
Multiple authentication methods support

### ISSUE THREAD

**Issue by azmeuk** [python-caldav/caldav#192]
Currently, only the first authentication method supported by a server is tried:

https://github.com/python-caldav/caldav/blob/c19abb303dc915cd8471628ef0a4f034204d1b5b/caldav/davclient.py#L549

However, sometimes servers support multiple authentication method, e.g. `Bearer` and `Basic`, but caldav will not attempt to connect if the unsupported method appears first in the `WWW-authenticate` header. For instance, this is the header provided by my server:

```
Bearer realm="Foobar", Basic realm="Foobar", charset="UTF-8", Basic realm="Foobar", charset="UTF-8", Basic realm="Foobar", charset="UTF-8"
```

Instead of just looking for the first authentication method in the header, I suggest to iterate over all the methods in the header until one is found that does not raise a `NotImplementedError`.

What do you think?

**Comment by tobixen** [comment]
Ouch.  I thought I had nailed this once and for all.  I guess I'll have to release a new minor version soon.

(IMO, I shouldn't really have to think about this ... IMO this logic should belong to the requests library)
