### ISSUE TITLE
Use pytest for unit tests

### ISSUE THREAD

**Issue by azmeuk** [python-caldav/caldav#196]
Hey o/
You said you are using nosetests to run unit tests, but nowadays pytest receive a lot more attention than nosetests, while being fully compatible.
What do you think of running tox and GHA tests with pytest?
If you are OK I can provide a patch for this.

**Comment by tobixen** [comment]
Absolutely.  I did read somewhere that nosetests was deprecated.

**Comment by tobixen** [comment]
I think this issue can be closed now?

**Comment by azmeuk** [comment]
Yes absolutely :+1:
