### ISSUE TITLE
sync-tokens support?

### ISSUE THREAD

**Issue by tonioo** [python-caldav/caldav#20]
I wonder if python-caldav supports sync-tokens?

**Comment by tobixen** [comment]
Probably not?  Do you have any information on those sync-tokens?

**Comment by tonioo** [comment]
I'm talking about https://tools.ietf.org/html/rfc6578. I've also read sabredav documentation which talks about them (http://sabre.io/dav/building-a-caldav-client/, section "Speeding up Sync with WebDAV-Sync") but I guess I can implement a similar mechanism using profind() and report() methods?

**Comment by tobixen** [comment]
Probably ... I have no idea on sync-tokens, probably it should be supported, but I don't have time to look into it anytime soon :-)

**Comment by tobixen** [comment]
This issue got duplicated.  Development of sync-collection support is now tracked in #87, so I'll close this issue.
