### ISSUE TITLE
Is it possible to share calendars with another user using caldav?

### ISSUE THREAD

**Issue by DeadScreams** [python-caldav/caldav#202]
Hello👋🏼
I am doing my project and I need to grant partial access to a user in my calendar. I tried to find the answer in the source code and in the RFC but couldn't. Mb I'm just inattentive, but I really need help. So, is it possible to share calendars with another user and how can I do it if possible?

**Comment by tobixen** [comment]
As far as I know, granting permissions is not supported through the caldav protocol ... though I may be wrong.  The relevant RFCs may be RFC4918 and RFC3744.

**Comment by tobixen** [comment]
Closing this one since there is no support for granting access rights through the CalDAV protocol.
