### ISSUE TITLE
test_create_ical fails on v0.10

### ISSUE THREAD

**Issue by Technetium1** [python-caldav/caldav#230]
Host OS is Arch.
A build log is here: [python-caldav.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/python-caldav.log)
Chaotic-AUR is tracking this failure here: https://github.com/chaotic-aur/packages/issues/735

**Comment by tobixen** [comment]
My hunch is that it's the new release of the icalendar library that is making a mess here.  I'm able to reproduce the breakage and will follow up.

**Comment by tobixen** [comment]
I've looked into it and concluded that it's the assert in the test code that is broken.  I will fix it.  I hope to be able to release v0.10.1 towards the end of the week.

**Comment by tobixen** [comment]
Sorry for this dragging out.  Version 0.11 has been released now.
