### ISSUE TITLE
Doc and examples: date_search is deprecated

### ISSUE THREAD

**Issue by tobixen** [python-caldav/caldav#233]
the `calendar.date_search`-method is redundant and deprecated.  Doc and examples needs to be rewritten to use `calendar.search` instead.

**Comment by yeshwantthota** [comment]
I want to work on this issue can you assign this to me?

**Comment by yeshwantthota** [comment]
> Sure.
> 
> `calendar.search` can almost be used as a drop-in replacement for `calendar.date_search`, it accepts all the same parameters, but with some few differences. Notably, `calendar.date_search` by default searches only for events, not tasks nor journals. Also, for `date_search`, the `expand` parameter defaults to `True` if both start and end is given, but it defaults to `False` for the search method. So the short story is that `calendar.search(start=ts1, end=ts2)` should be rewritten to `calendar.search(start=ts1, end=ts2, event=True, expand=True)`.

Thank you for the information.

**Comment by yeshwantthota** [comment]
@tobixen I made the necessary changes and raised the PR please review it.

**Comment by tobixen** [comment]
Resolved in #236.
