### ISSUE TITLE
Synctoken: invalid value

### ISSUE THREAD

**Issue by sm8ps** [python-caldav/caldav#234]
I set a sync token with a Nextcloud-24 server:
```
cal = dav_client.principal().calendar( calName )
objects = cal.objects()
syncToken = objects.sync_token
```
Its value is then 'http://sabre.io/ns/sync/3' which does not seem correct. -- Am I doing the right thing at all?

**Comment by tobixen** [comment]
`http://sabre.io/ns/sync/3` seems like a weird value, but please check that it works.

In my compatibility matrix it says that sync tokens works on Nextcloud ... all until one tries to delete an event from the calendar.  Then Nextcloud will send a "418 I'm a teapot" next time one is trying to do a sync using the sync-token.
