### ISSUE TITLE
Introduce type hints

### ISSUE THREAD

**Issue by tobixen** [python-caldav/caldav#251]
We ought to use type hints - though this depends on python2-support to be officially dropped (PR #228), this has been deliberately postponed as python2 is still supported by some OS distributions.

Help is wanted, I learned python while 2.4 was bleeding edge, type hints is new to me.  It's not needed to introduce type hints everywhere in one operation, pull requests that only takes parts and bits will be accepted.

**Comment by sim0nx** [comment]
I guess this one can be closed with the merge of https://github.com/python-caldav/caldav/pull/358

**Comment by tobixen** [comment]
Oh, a duplicate of #328?  Thanks for pointing out.
