### ISSUE TITLE
Parsing fails for events with a duration set to "DURATION:P"

### ISSUE THREAD

**Issue by sim0nx** [python-caldav/caldav#29]
Hi,

I am parsing a calendar which unfortunately has a number of events with the following entry:
DURATION:P

Which fails with
`lib/python3.6/site-packages/vobject/icalendar.py", line 1387, in transformToNative
    raise ParseError("DURATION must have a single duration string.")
vobject.base.ParseError: At line 14: DURATION must have a single duration string.
`
I am not sure if this is relevant but the event in question has the same end time as start time.

Any ideas ?

**Comment by sim0nx** [comment]
Issue related to vobject, not caldav. Closing issue here

**Comment by tobixen** [comment]
We may consider abandoning vobject eventually.

Anyway, it's interesting to know if this is a breach of the standard or not.  As I read https://tools.ietf.org/html/rfc5545#section-3.3.6 a single P without any trailing period information is invalid, hence it's not a bug in vobject.

There is always a question if one should create workarounds when software applications break the standard.  I think the most proper would be:

1) try to fix this issue at the producer side, as the producer of the ical data is breaching the standard.
2) if the above fails, make a filter before feeding the data to the caldav library, i.e. a regexp replace s/^DURATION:P$/DURATION:P0S/

**Comment by sim0nx** [comment]
Thanks for the feedback on this.

I agree that 1. would be best, but that is not likely to happen anytime soon (the client thunderbird/lightning).
Option 2 sounds doable, but that would have to done in caldav or am I wrong?

My current workaround is a fork of vobject where if this happends, I force a duration of 0s and all is fine.
Though of course I would very much prefer not to do it that way :-)

**Comment by tobixen** [comment]
Thunderbird Lightning is an open source product, isn't it?  Report the bug upstream, and perhaps it will be fixed.

I assume you have some interface code between Thunderbird and the python caldav library, that's where I would have put the workaround.

**Comment by sim0nx** [comment]
Sure, my point was that it would take a very long time before such a fix would land in my distro ;-)
Anyways, there is a caldav server (davical) involved. I will look into this more to be sure it is actually TB and not maybe davical, which does not conform to the RFC and have this reported wherever appropriate.

Thnx
