### ISSUE TITLE
sdist for 1.2.1 is missing on PyPI 

### ISSUE THREAD

**Issue by sunpoet** [python-caldav/caldav#305]
There is no sdist for 1.2.1 on PyPI. Is it possible to upload it? Thanks.

**Comment by tobixen** [comment]
Did I do something wrong when uploading v1.2.1?  My checklist says ...

```
rm dist/* 
python setup.py sdist bdist_wheel
ls -al dist
python -m twine upload dist/*
```

... though I may have missed something.  I'll try again.

**Comment by tobixen** [comment]
Please check if this is still an issue?

**Comment by sunpoet** [comment]
Thanks. It is no longer an issue.
