### ISSUE TITLE
Typo in v1.3.6 tag

### ISSUE THREAD

**Issue by fauxmight** [python-caldav/caldav#324]
For consistency (and for downsteam package maintainers), please change the tag from `1.3.6` to `v1.3.6`

**Comment by tobixen** [comment]
My goodness ... v1.3.x is really cursed.  At least I don't need to create a v1.3.7 due to this mistake :-)

**Comment by fauxmight** [comment]
Not critical at this point, but the `1.3.6` tag still shows in addition to a `v1.3.6` tag. I am not sure how to do so because I never had to, but you may want to remove the `1.3.6` tag.

**Comment by tobixen** [comment]
```
$ git push origin --delete 1.3.6
To github.com:python-caldav/caldav.git
 - [deleted]         1.3.6
```
