### ISSUE TITLE
nose and coverage should probably be test_requires

### ISSUE THREAD

**Issue by detrout** [python-caldav/caldav#33]
Hi,

I noticed that nose and coverage were listed in the set of install_requires, should they actually be tests_require? as they're only needed when running the unittest?

Perhaps something like this:

```
--- a/setup.py
+++ b/setup.py
@@ -27,5 +27,6 @@
         packages=find_packages(exclude="tests"),
         include_package_data=True,
         zip_safe=False,
-        install_requires=['vobject', 'lxml', 'nose', 'coverage', 'requests', 'six'],
+        install_requires=['vobject', 'lxml', 'requests', 'six'],
+        tests_require=['nose', 'coverage']
     )
```

**Comment by detrout** [comment]
(apparently the actual setup() attribute is tests_require) 

https://setuptools.readthedocs.io/en/latest/setuptools.html?highlight=tests_require
tests_require
    If your project’s tests need one or more additional packages besides those needed to install it, you can use this option to specify them. It should be a string or list of strings specifying what other distributions need to be present for the package’s tests to run. When you run the test command, setuptools will attempt to obtain these (even going so far as to download them using EasyInstall). Note that these required projects will not be installed on the system where the tests are run, but only downloaded to the project’s setup directory if they’re not already installed locally.

**Comment by tobixen** [comment]
Thanks.

**Comment by detrout** [comment]
You're welcome.
