### ISSUE TITLE
Getting ATTENDEE PARTSTAT value

### ISSUE THREAD

**Issue by GeorgeNikitinNV** [python-caldav/caldav#348]
Thanks for this nice lib, it really saves a lot of trouble!

Is there a way to get from `EVENT` a subj? From what I have found
```
event.icalendar_component.get("ATTENDEE")
```
returns only emails, but not the PARTSTAT value.

**Comment by GeorgeNikitinNV** [comment]
Have found the following solution, might be helpful for someone else:
```
event.icalendar_component.get("ATTENDEE")[0].params['PARTSTAT']
```

**Comment by tobixen** [comment]
This is outside the scope of the caldav library, that belongs to the icalendar library (I was recently aware that there also exists an ics library).  I found some code in the caldav library that I once wrote up to handle calendar invites ... but nevermind, I see you already found out of this :-)
