### ISSUE TITLE
HTTP/1.1 507 Insufficient Storage

### ISSUE THREAD

**Issue by ArtemIsmagilov** [python-caldav/caldav#353]
python code
```python
c.objects_by_sync_token()
```
error
```error
caldav.lib.error.ResponseError: ResponseError at 'HTTP/1.1 507 Insufficient Storage', reason no reason
```
But this code is working(need sync token)
```python
c.search(event=True)
```

**Comment by tobixen** [comment]
Problem at the server side.  Yandex?

**Comment by ArtemIsmagilov** [comment]
Hi, yes!

**Comment by tobixen** [comment]
Unfortunately, `objects_by_sync_token` does not work at all servers. :-(

**Comment by ArtemIsmagilov** [comment]
This method(`objects_by_sync_token`) working on Yandex, but crash when too many events on the calendar

**Comment by tobixen** [comment]
That's cool, you've discovered a scaling problem at the Yandex-side of things :-)  In any case the error message is thrown by the server and is not happening at the client side, so you should raise an issue with Yandex :-)
