### ISSUE TITLE
Search with dtstart==dtend

### ISSUE THREAD

**Issue by pizzle-d** [python-caldav/caldav#36]
Searching with date_search(start,end) does not work when dtstart is equal to dtend.

> 1   File "location/calendar/lib/python3.7/site-packages/caldav/objects.py", line 510, in date_search
>   2     Event(self.client, url=self.url.join(r), data=results[r][cdav.CalendarData.tag], parent=self))
>   3   File "location/calendar/lib/python3.7/site-packages/caldav/objects.py", line 724, in __init__
>   4     self.data = data
>   5   File "location/calendar/lib/python3.7/site-packages/caldav/objects.py", line 801, in _set_data
>   6     self._instance = vobject.readOne(to_unicode(self._data))
>   7   File "location/calendar/lib/python3.7/site-packages/vobject/base.py", line 1156, in readOne
>   8     allowQP))
>   9   File "location/calendar/lib/python3.7/site-packages/vobject/base.py", line 1128, in readComponents
>  10     component.transformChildrenToNative()
>  11   File "location/calendar/lib/python3.7/site-packages/vobject/base.py", line 674, in transformChildrenToNative
>  12     child.transformChildrenToNative()
>  13   File "location/calendar/lib/python3.7/site-packages/vobject/base.py", line 673, in transformChildrenToNative
>  14     child = child.transformToNative()
>  15   File "location/calendar/lib/python3.7/site-packages/vobject/base.py", line 185, in transformToNative
>  16     return self.behavior.transformToNative(self)
>  17   File "location/calendar/lib/python3.7/site-packages/vobject/icalendar.py", line 1454, in transformToNative
>  18     raise ParseError("DURATION must have a single duration string.")
>  19 vobject.base.ParseError: At line 27: DURATION must have a single duration string.

i hope someone can help me with this problem.

**Comment by tobixen** [comment]
Perhaps I should add some code here returning empty list if they are equal or in the wrong order. 

If dates are used, the end date will not be included in the search though honestly I'm uncertain how that works out wrg of time zones

**Comment by tobixen** [comment]
Wait, please disregard my last message.

This is either a bug in vobject, or is vobject rightly complaining on a breach of standards. 

I'm on the mobile now, will try to check a bit later why the object is instantiated. If there is not a very good reason for instantiating a vobject here, it should not be done.

**Comment by tobixen** [comment]
I discovered there is a function caldav.lib.vcal.fix which does various munging of non-compliant icalendar objects.  It may help to throw in more logic there.  It's dirty, I won't do it myself, but pull requests are accepted.

**Comment by tobixen** [comment]
I'm closing this one now as I don't believe this is a bug in the caldav library. I haven't investigated if the standard allows dtstart and dtend to be equal or not, but if not the bug is neither in vobject.

That said, with #43 done, hopefully calendar search will work despite vobject declining such objects.

You may try to write up a pull request removing the dtend from the icalendar eventually.

Closing this issue as for now.
