### ISSUE TITLE
get unique recurrence event

### ISSUE THREAD

**Issue by ArtemIsmagilov** [python-caldav/caldav#362]
i need get unique reccurence event but, if using `event_by_uid` i get not reccuence event

**Comment by tobixen** [comment]
All recurrence objects share the same uid.  A recurrence object is identified by the uid plus the recurrence-id, which is a datetime/date property.  I didn't test (and the behaviour is most likely to depend on the server side anyway), but you may try to do something like `calendar.search(uid=uid, start=some_timestamp-small_timedelta, end=some_timestamp+small_timedelta)`.
