### ISSUE TITLE
.todos() ignores all tasks without a progress status

### ISSUE THREAD

**Issue by daehruoydeef** [python-caldav/caldav#38]
I am running version 0.5 and I cannot get my todos without the status. I thought it would be fixed since [this issues](https://github.com/python-caldav/caldav/issues/14). I am only getting the todos to sync on which I set a status, however all tasks sync (including the finished one) when I set the `include_completed=True` parameter.

**Comment by tobixen** [comment]
I think this is sort of a duplicate of #14.  I will close this one and keep #14 open.

Which caldav server version do you use?
