### ISSUE TITLE
Baikal servers reportedly throwing 405 and 500 under HomeAssistant

### ISSUE THREAD

**Issue by tobixen** [python-caldav/caldav#384]
Ref https://github.com/home-assistant/core/issues/111421 and https://github.com/home-assistant/core/issues/111432

If I get some username/password/URL that I could use, I may try to run the caldav functional tests towards the servers in question.

**Comment by Skaronator** [comment]
You could start up a local container using the container image https://github.com/ckulka/baikal-docker

After startup you can access the admin ui and create an account for home assistant.

**Comment by tobixen** [comment]
From the information in the HomeAssistant tickets, this seems to be some bug in Baikal that is triggered by the HomeAssistant caldav integration, and not by the python-caldav library.  I have run all the functional tests successfully towards the baikal server.  Well, I could look more into what HomeAssistant is actually doing here and try to reproduce the problems in functional tests, but I'm more tempted to state "not my problem" and close this issue without further ado.  (but I have a low threshold of reopening it).

**Comment by Skaronator** [comment]
Alrighty thanks for the quick response!

**Comment by voronind-com** [comment]
This is still relevant, thank you.
