### ISSUE TITLE
Change default User-Agent?

### ISSUE THREAD

**Issue by tobixen** [python-caldav/caldav#391]
Also ref https://github.com/home-assistant/core/issues/105292

The default User-Agent is set to `Mozilla`, I'm considering to change it to `python-caldav` or something like that. 

The Mozilla default was set by @cyrilrbt  in 2010 or earlier.  Was there any reason for choosing Mozilla rather than something else?  Also, could there be caldav servers out there that behaves differently dependent on the User-Agent header? Even the most innocent changes in this code has caused breakages on weird servers and inbound bug reports - and I've seen systems blocking traffic based on the User-Agent.  Perhaps it's best not to jinx the default setting?

**Comment by cyrilrbt** [comment]
IIRC I set it to mozilla because some service was blocking me without a user agent, so this might be a breaking change.
