### ISSUE TITLE
Tag new versions

### ISSUE THREAD

**Issue by Phyks** [python-caldav/caldav#4]
Hi,

There are some Git tags for versions up to 0.3. Would it be possible to add also git tags for versions 0.4 and 0.5?

I tend to think this is clearer than branches to show where a particular version stopped, but more important I think it is really useful to have a single way to pinpoint versions (either tags or branches, but not a mix, as it confuses people).

Thanks!

**Comment by tobixen** [comment]
oh, I'm not receiving subscriptions on new issues here - so sorry for the delay.

I've fixed this.

**Comment by Phyks** [comment]
Thanks!
