### ISSUE TITLE
Make logging configurable through environment variables

### ISSUE THREAD

**Issue by tobixen** [python-caldav/caldav#426]
The caldav library does produce log noise when used towards popular but non-conforming calendar servers.  There is a wish to mute such logging i.e. by setting up environmental variables for it.  See also https://github.com/home-assistant/core/issues/111633

**Comment by MrEbbinghaus** [comment]
(This also comes from Home Assistant as well.)

Logging the messages as 'Error' seems inappropriate, with the message _This is probably harmless, ..._ being logged after the lib has detected and fixed a problem. 

Also, to avoid confusing log entries without a message, the diff log should either always be at debug level, or even better, included in the previous log. 
https://github.com/python-caldav/caldav/blob/4c381834953b0d64a2afbc0ad0b6268670e56883/caldav/lib/vcal.py#L108-L114

**Comment by tobixen** [comment]
Great.  Would you mind creating a pull-request?

**Comment by Gloomyeye** [comment]
Great to here that the logging will be better. It would be nice to change the logging object in the HA log entry from root to a caldav specific logging object of possible.
