### ISSUE TITLE
Possibly the server has a path handling problem, possibly the URL configured is wrong.

### ISSUE THREAD

**Issue by dieterbahr** [python-caldav/caldav#428]
I have an error message because of Caldav on a Synology 

Source: /usr/local/lib/python3.12/site-packages/caldav/objects.py:303 Possibly the server has a path handling problem, possibly the URL configured is wrong. Path expected: /caldav/, path found: ['/caldav.php/'] Please raise an issue at https://github.com/python-caldav/caldav/issues or reach out to t-caldav@tobixen.no , include this error and the traceback and tell what server you are using. 

Continuing, probably everything will be fine Everything works, the link is correct and the calendar is displayed in Homeassistant.
Core: 2024.7.3, Supervisor: 2024.06.2, OS 12.4 ,Synology DSM: DSM 7.2.1-69057

Thanks

**Comment by tobixen** [comment]
I believe this is a known problem with Synlogy, and I believe it can be worked around by tweaking the configured caldav URL to include `.php`
