### ISSUE TITLE
search events results with NotImplementedError

### ISSUE THREAD

**Issue by paramazo** [python-caldav/caldav#429]
I try the code from examples here:

https://github.com/python-caldav/caldav/blob/b5803fff63464a6e02c216fd24ca06dfc4d02f09/examples/basic_usage_examples.py#L201

It throws a NotImplementedError exception

```
Traceback (most recent call last):
  File "/home/user/form2calender.py", line 284, in <module>
    main()
  File "/home/user/form2calender.py", line 111, in main
    add_event(form_name, res)
  File "/home/user/form2calender.py", line 252, in add_event
    events_fetched = calendar.search(
  File "/home/user/.local/lib/python3.9/site-packages/caldav/objects.py", line 1072, in search
    (xml, comp_class) = self.build_search_xml_query(
  File "/home/user/.local/lib/python3.9/site-packages/caldav/objects.py", line 1320, in build_search_xml_query
    raise NotImplementedError("searching for %s not supported yet" % other)
NotImplementedError: searching for events not supported yet
```

Iam using caldav 1.3.9 with python 3.9.2

**Comment by tobixen** [comment]
> I try the code from examples here:
> 
> https://github.com/python-caldav/caldav/blob/b5803fff63464a6e02c216fd24ca06dfc4d02f09/examples/basic_usage_examples.py#L201

Uff.  I need to make sure that the examples code is actually run in the test suite, and at least prior to releases.  But actually, I've been running the examples code now both towards 1.3.9 and master now, without breakages.  Weird.

> It throws a NotImplementedError exception

I think you wrote `events` when it should have been `event`.

I probably should consider some better error message than a `NotImplemented`-error for misspellings like that.  Allowing `events`, `todos` and `journals` as synonyms for `event`, `todo` and `journal` could be another option.
