### ISSUE TITLE
Can't open my Baikal calDAV with caldav

### ISSUE THREAD

**Issue by TravelTrader** [python-caldav/caldav#50]
I'm sorry to ask you but I tried every possible format for the URL and I didn't get access to my data with this python library.

My Baikal server runs at `https://myserver.de/Baikal/`.

And I tried `.../cal.php/principals/myusername/`, `.../cal.php/calendars/myusername/oneofthecalendars` and much more. And just the server name, too. But it didn't work.

The first part of my script is just:
```
caldav.DAVClient(url, user, pwd)
principal = client.principal()
```
And the second line results in an error:
```
requests.exceptions.ProxyError: HTTPSConnectionPool(host='myserver.de', port=443): Max retries exceeded with url: /Baikal/cal.php/calendars/myusername/oneofmycalendars/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5ff9b4a630>: Failed to establish a new connection: [Errno -2] Name or service not known',)))
```

Maybe you can help me with that issue to get Baikal running within my Python codes.
Thanks a lot!

**Comment by tobixen** [comment]
"Name or service not known" means that either the local DNS configuration is wrong, or that myserver.de does not exist.  myserver.de does seem to exist, so that's strange.  This error means that we're at all unable to contact the server, hence it doesn't matter if the path is correct or not.

**Comment by TravelTrader** [comment]
Thanks for you reply. That's strange. Because I tried exactly the link I use on iOS for example.

Do you have an idea how to solve that? I use `python3` under `Ubuntu 18.04`. And I have several py-files using online data.

Only the first line of code and then a `print(client)` results in
```
<caldav.davclient.DAVClient object at 0x7fc004adc5c0>
```
At which point can I change anything?

**Comment by tobixen** [comment]
I just noticed this one in the error message:

    Caused by ProxyError('Cannot connect to proxy.'

The error is due to incorrect proxy settings?

**Comment by TravelTrader** [comment]
> The error is due to incorrect proxy settings?

I'm surprised, too. I do not have any proxy! And I didn't set any proxy changes.
What could that be?
How can I find a solution??

**Comment by tobixen** [comment]
Ah, here is the error:

    caldav.DAVClient(url, user, pwd)

while DAVClient.__init__ is defined like this:

    def __init__(self, url, proxy=None, username=None, password=None,
                 auth=None, ssl_verify_cert=True):

so you have to do it like this:

    caldav.DAVClient(url=url, username=user, password=pwd)

Admittedly bad design, "proxy" is probably the least used parameter and therefore ought to be the last one.  The reason why it got like this is that the proxy parameter was introduced prior to username and password (in earlier versions of caldav, those were to be passed as a part of the URL), and things cannot be easily changed (or else backward compatibility would be lost).
