### ISSUE TITLE
Two license files present - which one is right?

### ISSUE THREAD

**Issue by Achimh3011** [python-caldav/caldav#60]
There is one GPLv3 license file and one with Apache 2.0. Dual licensing makes no sense here, as Apache v2 can already be used together with GPLv3.

I'd prefer Apache 2.0 in order to license a derived package as Apache 2.0 itself.

**Comment by tobixen** [comment]
Eventually, @cyrilrbt would have to answer this one.  Personally I see no issue with dual licensing, even if the licenses are considered to be compatible ... it does give the freedom to create derivative work and stick to one of the two licenses.

**Comment by cyrilrbt** [comment]
I don't see the issue here, use either license.
