### ISSUE TITLE
Documentation should be refreshed

### ISSUE THREAD

**Issue by tobixen** [python-caldav/caldav#67]
Ref #54 ... the online documentation points to version 0.5.0.  Everything should be reviewed.  Is the example code still best practice?  Is the other content there up-to-date?

**Comment by snoopyjc** [comment]
LOL what documentation?

**Comment by ericfrederich** [comment]
@snoopyjc 
README.md has a documentation link to http://packages.python.org/caldav.  On that page there is a "More examples" section which has a link to BitBucket https://bitbucket.org/cyrilrbt/caldav/src/default/tests/test_caldav.py?at=default

**Comment by tobixen** [comment]
Well, the documentation here is up-to-date now, but the README still points to https://pythonhosted.org/caldav and there is only the old documentation ... @cyrilrbt ... how to update it on pythonhosted.org?

**Comment by cyrilrbt** [comment]
That’s actually a great question. I don’t have a clue, I can’t even find a homepage or contact info. Was it just a mirror site that is no longer maintained and broke?

**Comment by tobixen** [comment]
If it's a mirror, perhaps it's https://readthedocs.org/projects/caldav/ that should be updated

**Comment by cyrilrbt** [comment]
That, I had access to. I set it up a while back and it has to be rebuilt manually. I didn’t see a point in keeping it so I deleted it.

**Comment by tobixen** [comment]
https://pythonhosted.org/an_example_pypi_project/buildanduploadsphinx.html seems relevant, I'll look into it

**Comment by tobixen** [comment]
Seems slightly abandoned, the sphinx_pypi_upload library hasn't been rewritten for python3-compatibility.  I found a sphinx_pypi_upload3 package, but then I got a 405 error that I can't do a POST to https://upload.pypi.org/legacy/ ... weird.

On https://packaging.python.org/tutorials/creating-documentation/ it says nothing except "This section covers the basics of how to create documentation using Sphinx and host the documentation for free in Read The Docs." - and a link to https://docs.readthedocs.io/en/latest/intro/import-guide.html

I suppose hosting the documentation at pythonhosted.org (packages.python.org redirects to pythonhosted.org) is legacy and that readthedocs is supposed to be used.  Hm.

Reopening this issue - while I have completed the task of "refreshing the doc", it's pretty moot without uploading the documentation somewhere.

**Comment by tobixen** [comment]
Docs are now on readthedocs, they are auto-refreshed whenever someone pushes to github, and the pointer from the README is now correct, but I just noticed one major flaw with the readthedocs documentation - the autogenerated parts of it is not included :-(

**Comment by tobixen** [comment]
I give it up as for now - will create a separate issue for the readthedocs and defer it to later.
