### ISSUE TITLE
0.6.2-release

### ISSUE THREAD

**Issue by tobixen** [python-caldav/caldav#68]
@cyrilrbt, I think it's time for another minor release.

Quite some embarrassing bugs have been found in 0.6.1, I hope they are properly ironed out now.  To reduce the risk of new bugs entering the master branch, by now unit tests and functional tests are run every time commits are pushed to github, or pull requests are submitted. 
 Still, the 0.6.2-release is admittedly under-tested - the public test servers I was running towards are currently down.  Anyway, I believe the risk of introducing new bugs is low compared to the benefit of ironing out known bugs.

Here are the release-notes:

* The timezone handling introduced in 0.6 was not very well tested, thanks to feedback from Achim Herwig this has been fixed.  In python 3.6 and higher, it's possible to convert between local time and utc without introducing the pytz/tzlocal dependencies.
* Quite some other bugs have been found and fixed.
* Some work has been done with the test framework:
  * Since the external public test servers have been notoriously unreliable, by default the tests will not be executed towards the external public test servers (and they are all down as of writing)
  * Xandikos is written in python, can be spawned up easily from python and has no other run-time dependencies than write access to a file system.  Spawning up a xandikos server instance from the test code was an easy thing to do, so by default now the tests are executed towards Xandikos.  However, Xandikos is python3-only, so this only applies when running tests from python3.
  * Unit tests are now run on every commit pushed to github, and on every github pull request.  This should stop the most embarrassing bugs from entering the master branch.

CAVEAT 1: some of the timezone handling has been moved from object.py to elements/cdav.py, and a minor incompatibility with 0.6.1 has been introduced; if you were using cdav/elements.py directly (and not using the higher-level methods in objects.py) and passing naive timestamps to it, they would be treated as UTC-time in 0.6.1 while they are assumed to be localtime in 0.6.2.  It seems very unlikely that this incompatibility issue would hit anyone.
CAVEAT 2: The 0.6.2-release is under-tested, all the servers/accounts used when testing 0.6.0 is currently down or unavailable.  (Please help!  Check tests/conf_private.py.EXAMPLE).

**Comment by cyrilrbt** [comment]
I'm kind of busy at the moment, just moved long distance, but I'll check it out by the end of the weekend at the latest. Though at first glance it sounds like a 0.7.0 to me, even though we never explicitly said we were doing semver. I think we should probably make that explicit. Again, this is just after a quick read of this issue only, I'll get back to you very soon!

-------- Original Message --------

**Comment by tobixen** [comment]
There are no new features, only bugfixes, hence I feel we should stay on 0.6.  For anyone to be affected by the minor incompatibility issue, they should be:

* Using cdav.timerange or cdav.expand directly.  Those attributes are only used when searching the calendar, and I believe most people would use Calendar.date_search for that (though, admittedly, if one wants to use complicated searches, Calendar.date_search may be insufficient).
* Already installed or upgraded to 0.6 and expecting same behavior in 0.6.2 (after all, 0.6 hasn't been out for long).
* Either being dependent on naive timestamps being interpreted as UTC-time by elements.cdav.timerange or making a slightly more sophisticated work-around on it than always searching for a bigger date range than needed.  I think many users may just observe the assume-naive-timestamp-is-utc as a "weird bug".

Hence I think it's a non-issue.

Wrg of semver, don't forget point 4 there ... https://semver.org/#spec-item-4 ... it's perfectly OK to have some API instability for versions lower than 1.0.0.

I'd suggest a feature-freeze and release 1.0.0 once the documentation has been properly done and more testing has been done.  Alternatively, if it's needed with more tweaks to ensure compatibility with iCloud or Exchange, it may be possible to release a 0.7.0.

**Comment by tobixen** [comment]
I forgot, it's also the icalendar vs vobject issue.  Since someone took over the maintainer role for vobject and since it now supports python3, there has been no urge to move over to icalendar - still, there are users who request support for icalendar objects, and I concluded vobject was a dire mess when I looked into it myself.  There is one open pull request for moving over to icalendar, and I believe someone else has also written patches for it, my concern is just that it breaks backward compatibility.

I would like to fix it so that icalendar objects are used internally, and let vobject be an optional dependency.  The old methods will be deprecated, but will still yield vobjects (if the module is installed).  New methods will yield an icalendar or vobject, dependent on what the caller wants.

This should probably be fixed prior to 1.0.  I don't think it's a big job.

**Comment by cyrilrbt** [comment]
OK, sounds good to me then. Let me know when master is ready to be built and published. Could you also pm me your pypi username? I don't see any reason for me to be a bottleneck for pushing out new releases :)

**Comment by rzolau** [comment]
Hi, do you have timeline for 0.6.2 to be pushed to pypi? Thanks for all the work!

**Comment by rzolau** [comment]
Bump?

**Comment by nic0dk** [comment]
any update on this @tobixen  ;)

**Comment by tobixen** [comment]
I'm offline today, but tomorrow it's promised rain, so there is a chance I'll get to it tomorrow :) Sent from my Huawei phone-------- Original Message --------Subject: Re: [python-caldav/caldav] 0.6.2-release (#68)From: Martin Nicolaisen To: python-caldav/caldav CC: Tobias Brox ,Mention any update on this @tobixen  ;)

**Comment by tobixen** [comment]
Let's see ... we've actually been more or less ready for releasing 0.6.2 since May.

* Unit tests passes.
* Functional tests passes on python3 towards xandikos.
* Version number in setup.py has been bumped.
* ChangeLog is up-to-date
* Functional tests towards my own calendar servers ... running ... fails with "424 dependency error" towards zimbra, but I believe that's a problem on my side.  One test fails with "500 internal server error" towards my old davical installation, but I also believe that's on my side.
* Functional tests towards public test servers ... all of them are down, and I don't have capacity fixing that right now.

For a minor-release it's OK that it hasn't been tested towards all possible caldav server implementations, but I'm not entirely happy that I haven't successfully tested this on python2 towards any caldav servers.  Could anyone help?  Install python modules `nose`, `coverage`, `tzlocal`, `pytz` and `xandikos`, copy tests/conf_private.py.EXAMPLE to tests/conf_private.py and edit, run nosetests.  The tests can be run towards a personal calendar and will clean up all the mess after itself without deleting anything else ... but don't shoot me if something goes wrong :-)

@cyrilrbt my pypi username is tobixen

**Comment by tobixen** [comment]
This is a bit critical, the current 0.6.1 is broken, and the current master branch does indeed work for me.  Perhaps we should consider to release without running the tests.

It shouldn't be much work getting up some calendar server and run the tests towards them ... but I'm unfortunately 100% busy for the weekend now. :-(

**Comment by tobixen** [comment]
Oh man, this was just biting me today.  Wanted to demonstrate my calendar-cli tool for a colleague, but it's broken with caldav 0.6.1.  I'll try to put up a test server after lunch and see if I can run the tests so we finally can push out a 0.6.2-release.

**Comment by tobixen** [comment]
All tests passes on baikal on python2 as well as python3.

**Comment by tobixen** [comment]
@cyrilrbt , did you give me permission to the project at pypi yet?  I guess not, since it's not visible there ...? :-)

**Comment by cyrilrbt** [comment]
I haven't, I don't think you sent me your pypi username. Send it over :)

--
Cyril Robert
+1.514.716.9974
cyrilrobert.org

-------- Original Message --------

**Comment by tobixen** [comment]
tobixen

**Comment by cyrilrbt** [comment]
Thanks! You've been added!

-------- Original Message --------

**Comment by tobixen** [comment]
I've gone AFK. Can you fix a 0.6.2-release?

**Comment by cyrilrbt** [comment]
I don't have access to my computer either

-------- Original Message --------

**Comment by tobixen** [comment]
I eventually managed to release it at 2019-11-22, so closing this issue now :-)
