### ISSUE TITLE
implement ctag/etag based sync from (and maybe to) server

### ISSUE THREAD

**Issue by dz0** [python-caldav/caldav#69]
Hi, 

the (old fashioned) sync-flow is described http://sabre.io/dav/building-a-caldav-client/ - it uses `etag`s for event change tracking. 

Could someone elaborate (give hints where what to change) if I want to have :

most important

1) `date_search`/`events` could return `etag`:
    - alongside `calendar-data` (for initial sync)
    - without `calendar-data` (to check for changes)
    - ps.: `date_search` seems to be generalization of `events` (but for now not DRY)?

-----
less important 

2) [`ctag`](https://github.com/apple/ccs-calendarserver/blob/master/doc/Extensions/caldav-ctag.txt)
`getctag`, which is from "http://calendarserver.org/ns/" namespace which I don't find mentioned in source (should be similar to `getetag`)...

3) `calendar-multiget` REPORT (for batched get) 

4) if-Match header support  (for "to server" update/delete)

ps.: I need this for SOGo and [Google CalDaV API](https://developers.google.com/calendar/caldav/v2/guide#specifications)

**Comment by tobixen** [comment]
At least I don't have any time to look into this in August, and probably not in September either.  In general I'm pretty liberal on accepting pull requests, though the test code needs to be run flawlessly against multiple server implementations before we're making a new minor-release.

**Comment by dz0** [comment]
my monkey-patch'es to use current caldav with google to sync via ctag/etag
https://gist.github.com/dz0/dbac261cf85b82a8146d41d2da21c6e8

ps.: sorry no time to play with patching caldav directly, but hopefully you can pick what seems worth

**Comment by tobixen** [comment]
Sort of duplicated in #81 - and there it's written that sync-collection is to be used rather than ctag.  Hm.

**Comment by tobixen** [comment]
https://github.com/apple/ccs-calendarserver/blob/master/doc/Extensions/caldav-ctag.txt is quite clear that ctag is deprecated.  I'll close this one and follow up with sync-collection in #87
