### ISSUE TITLE
date_search result items are always Events (though compfilter allows also TODO)

### ISSUE THREAD

**Issue by dz0** [python-caldav/caldav#70]
https://github.com/python-caldav/caldav/blob/master/caldav/objects.py#L601
```            matches.append(
                Event(self.client, url=self.url.join(r),
                      data=results[r][cdav.CalendarData.tag], parent=self))
```
I stumbled when comparing `date_search` to `events`, but didn't test anything...
For me, seems that instead `Event`, class should be dispatched by `compfilter` param.

**Comment by dz0** [comment]
seems, could use 
```
                data=results[r][cdav.CalendarData.tag]
                Klass = self._calendar_comp_class_by_data(data) # as in `object_by_uid`
                Klass(self.client, url=self.url.join(r), data=data, parent=self))

```

**Comment by tobixen** [comment]
The docstring says that compfilter can be set to "None" to fetch everything, so this is clearly a bug.  The presented solution would probably work (I'd prefer `comp_class` to `Klass` as variable name here), but it's needed to write up test code.  Unfortunately I don't have capacity to do any work here this month, but I'd happily accept a pull request if test code is included.
