### ISSUE TITLE
event_by_uid   might better use GET (reuse event_by_url), as prop-filter is not well supoerted (by for example Google)

### ISSUE THREAD

**Issue by dz0** [python-caldav/caldav#72]
Google caldav returns whole collection ignoring prop-filter :/ https://stackoverflow.com/questions/36749307/google-caldav-ignoring-filter-options

**Comment by tobixen** [comment]
Perhaps a try-except would do?  Or are there any advantages using prop-filter, maybe GET should always be used?

**Comment by tobixen** [comment]
I've looked into it, and I'm not sure it's possible to find some solution that isn't google-specific.

If you know the URL for an event, you may as well use the event_by_url method.
