### ISSUE TITLE
event object properties

### ISSUE THREAD

**Issue by dusscloud** [python-caldav/caldav#73]
Hi

I am discovering caldav so this is maybe a dummy question.
I successfully fetch calendars and retrieve event using the date_search.
But I don't get how I get details from each event. What are the event objects properties available ?
Let's say I want to get start and end of each event I retrieve from a date_search

**Comment by tobixen** [comment]
Sorry for the late reply.

date_search will yield a list of events, where event is a `caldav.Event`.  The ical string can be accessed through the data property.  The event properties can be accessed by converting it into a vobject object, using the property vobject_instance.  In the future, there will also be an icalendar_instance, ref https://github.com/python-caldav/caldav/issues/1

```python
events = date_search(...)
first_event = events[0]
print("remember " + first_event.vobject_instance.vevent.summary)
print(first_event.data)
```

**Comment by dusscloud** [comment]
Thanks.
For future readers, typically gettting start end end date is something like
`print("Start : " + str(first_event.vobject_instance.vevent.dtstart.value))
print("End : " + str(first_event.vobject_instance.vevent.dtend.value))`
