### ISSUE TITLE
Use Makefile and/or tox?

### ISSUE THREAD

**Issue by sblondon** [python-caldav/caldav#77]
Are you interested to have a Makefile to execute usual commands (like `make test`, `make doc` and `make package`)?

More or less related, why not using [tox](https://tox.readthedocs.io/en/latest/) to run test locally with python 2.7 and python3 at the same time?

If you think it's a good idea, I will provide a PR.

**Comment by tobixen** [comment]
Tox is a good idea. I'm not sure if a Makefile is useful, are there many other python libraries coming with a Makefile?Sent from my Huawei phone

**Comment by tobixen** [comment]
Perhaps it's because I'm not familiar with tox, but my experience is that debugging is easier with nose than tox. It should probably be fixed in such a way that it's possible to use both tox and nose.

**Comment by sblondon** [comment]
1. I don't know if there are lot of python libraries with a Makefile. I made three attempts:
 * Makefile in [requests](https://github.com/psf/requests) library
 * not in `nose` library
 * not in `pytest` library

With a Makefile, there is only one point to find main features of the package and how it's done internally. 

2. To me, the main advantage to `tox` is to easily run the tests on several python versions. If `nose` can do it, perhaps the idea can be forgotten? To run tox, we can add parameters to `setup.cfg` or add a new file (`tox.ini`).

Parameters in `setup.cfg` would be something like:
```
[tox:tox]
envlist = py27,py36,py37
```

Feel free to accept/refuse one or both ideas.

**Comment by tobixen** [comment]
I see no significant disadvantages neither in having a tox-section in the setup.cfg nor a Makefile, so I will accept a pull request eventually.

**Comment by tobixen** [comment]
Sorry for the delay.  All that was needed was a five minute review and pressing a button, but I'm quite swamped nowadays.  Anyway, I'm prioritizing calendar-cli and python-caldav this month.
