### ISSUE TITLE
caldav.lib.error.NotFoundError: 207 Multi-Status

### ISSUE THREAD

**Issue by embie27** [python-caldav/caldav#79]
I have the UID of an event and try to get it by using `client.principal().calendar("Calendar").event("uid")` but I always get the following error message:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/ùser/Dokumente/RaspberryPi/Francis2/venv/lib/python3.7/site-packages/caldav/objects.py", line 737, in event_by_uid
    return self.object_by_uid(uid, comp_filter=cdav.CompFilter("VEVENT"))
  File "/home/user/Dokumente/RaspberryPi/Francis2/venv/lib/python3.7/site-packages/caldav/objects.py", line 731, in object_by_uid
    raise error.NotFoundError(errmsg(response))
caldav.lib.error.NotFoundError: 207 Multi-Status
b'<?xml version="1.0"?>\n<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:fx="http://fruux.com/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:card="urn:ietf:params:xml:ns:carddav"/>\n'
```

**Comment by microbrewer** [comment]
Having the same issue :(

**Comment by tobixen** [comment]
Which calendar server are you using?

----- On Feb 2, 2020, at 1:44 AM, microbrewer notifications@github.com wrote:

> Having the same issue :(
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/python-caldav/caldav/issues/79#issuecomment-581084986

-- 
Tobias Brox
Senior System Consultant
Redpill Linpro AS - Changing the game
Mobil: +47 917 000 50 
Kontor: +47 215 441 68

**Comment by microbrewer** [comment]
I'm Using Nextcloud 17 as CaldavServer. And I'm not actually using caldav lib directly, but calendar-cli with `--todo-uid` parameter. But the error seems to be the same, if it isn't I apologize for the confusion: 

```
File "/usr/local/lib/python2.7/dist-packages/caldav-0.6.2-py2.7.egg/caldav/objects.py", line 802, in object_by_uid
    raise error.NotFoundError(errmsg(response))
caldav.lib.error.NotFoundError: 207 Multi-Status

<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"/>
```

**Comment by tobixen** [comment]
>  I'm not actually using caldav lib directly, but calendar-cli with --todo-uid parameter. 

doesn't really matter, the error clearly comes from the caldav library ... except ... are you sure the item with said uid exists?  I get the same error if I enter some random uid.

    $ python3 ./calendar-cli todo --todo-uid a75ab88c-1d82-11e5-aec9-9c8e99d15218 list
    2018-08-07 (Tue)! 2018-12-28 (Fri)! b'flytte stengeventil gass'
    here be dragons - calendar-cli is not properly tested for python3.  See 
    https://github.com/tobixen/calendar-cli/issues/33

```
$ python3 ./calendar-cli todo --todo-uid bar-foo-zoo list
here be dragons - calendar-cli is not properly tested for python3.  See https://github.com/tobixen/calendar-cli/issues/33Traceback (most recent call last):
  File "./calendar-cli", line 936, in <module>
    main()
  File "./calendar-cli", line 933, in main
    ret = args.func(caldav_conn, args)
  File "./calendar-cli", line 645, in todo_list
    tasks = todo_select(caldav_conn, args)
  File "./calendar-cli", line 535, in todo_select
    tasks = [ find_calendar(caldav_conn, args).object_by_uid(args.todo_uid) ]
  File "/usr/lib/python3.8/site-packages/caldav-0.6.2-py3.8.egg/caldav/objects.py", line 802, in object_by_uid
    raise error.NotFoundError(errmsg(response))
caldav.lib.error.NotFoundError: 207 Multi-Status

b'<?xml version="1.0" encoding="utf-8" ?>\n<multistatus xmlns="DAV:"/>\n'
```

**Comment by tobixen** [comment]
(if that is the real issue here, then ... I agree the error message is quite confusing)

**Comment by microbrewer** [comment]
I am pretty sure the item with the UID exists:

```
$ calendar-cli --config-file cal.conf --calendar-url XXX todo add test
Added todo item with uid=1a4b5204-468a-11ea-968f-54ee750af563

$ calendar-cli --config-file cal.conf --calendar-url XXX todo --todo-uid 1a4b5204-468a-11ea-968f-54ee750af563 list
Traceback (most recent call last):
  File "/usr/local/bin/calendar-cli", line 4, in <module>
    __import__('pkg_resources').run_script('calendar-cli==0.0.0', 'calendar-cli')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/calendar_cli-0.0.0-py2.7.egg/EGG-INFO/scripts/calendar-cli", line 937, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/calendar_cli-0.0.0-py2.7.egg/EGG-INFO/scripts/calendar-cli", line 934, in main
    
  File "/usr/local/lib/python2.7/dist-packages/calendar_cli-0.0.0-py2.7.egg/EGG-INFO/scripts/calendar-cli", line 646, in todo_list
    
  File "/usr/local/lib/python2.7/dist-packages/calendar_cli-0.0.0-py2.7.egg/EGG-INFO/scripts/calendar-cli", line 536, in todo_select
    
  File "/usr/local/lib/python2.7/dist-packages/caldav-0.6.2-py2.7.egg/caldav/objects.py", line 802, in object_by_uid
    raise error.NotFoundError(errmsg(response))
caldav.lib.error.NotFoundError: 207 Multi-Status

<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"/>
```
I also took a manual look into the server's database and a mysql select for the specified UID returns the following event:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//tobixen//calendar-cli//EN
BEGIN:VTODO
DTSTAMP;VALUE=DATE-TIME:20200203T133554Z
DTSTART;VALUE=DATE:20200204
DUE;VALUE=DATE:20200204
STATUS:NEEDS-ACTION
SUMMARY:test
UID:1a4b5204-468a-11ea-968f-54ee750af563
END:VTODO
END:VCALENDAR
```
Hope this helps.

**Comment by tobixen** [comment]
I will try to install nextcloud to see if I can reproduce this

**Comment by microbrewer** [comment]
I took a look at my Nextcloud logs and whenever I try to list items, the following comes up:

```
[webdav] Debug: Sabre\DAV\Exception\NotAuthenticated: No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured [...]
```
Not sure if this is really related because I also see this message when just doing a general "todo list", which is working fine regardless. On the other hand, adding an item does not produce this message, nor do any of my other clients. Will do some more digging if this might be a fault in my server config though...

**Comment by tobixen** [comment]
Hm.

In davclient.py, there is extensive usage of logging.debug, everything sent to and from the caldav server can be captured as debug logging - but by default, the debug logging is discarded.  calendar-cil has a command line option --debug-logging, but unfortunately this option seems to do nothing.  That's eventually a bug in calendar-cli that ought to be fixed.

**Comment by microbrewer** [comment]
Great, thanks. Will play around with that a bit! :)

**Comment by tobixen** [comment]
Authentication headers are sent separately through the requests library, and are not included in the debug output.  Also, I possibly I found the reason for that debug outputs from nextcloud.  davclient.py, around line 246.  auth is constructed as a request.auth.HTTPDigestAuth, the request is sent to the server, and if we get a 401, a new request is immediately fired off using request.auth.HTTPBasicAuth.  Meaning that for servers supporting basic auth but not digest auth, every request will be sent twice to the server.  This could most likely be designed a bit better ...

**Comment by microbrewer** [comment]
Ok, yeah I can confirm that from the davclient debug logs. For the first connection (digest?), the server always responds with a 401 and for the second (basic auth?) with a 207 multistatus. Only if I query for a UID, the 207 just comes up empty. For the general "todo list" it contains all the data...

**Comment by microbrewer** [comment]
Ok, I think I've hit a personal dead end. This is what davclient.py sends when querying for a UID (unsuccessfully on my server):
```
<C:calendar-query xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:D="DAV" xmlns:I="http://apple.com/ns/ical/"><ns0:prop xmlns:ns0="DAV:"><C:calendar-data/></ns0:prop><C:filter><C:comp-filter name="VCALENDAR"><C:prop-filter name="UID"><C:text-match collation="i;octet">7f88a43e-487c-11ea-a65d-902b34303921</C:text-match></C:prop-filter></C:comp-filter></C:filter></C:calendar-query>
```
And this is what one of my other clients sends when querying for the same UID (sucessfully):
```
<x1:calendar-query xmlns:x1="urn:ietf:params:xml:ns:caldav"><x0:prop xmlns:x0="DAV:"><x0:getcontenttype/><x0:getetag/><x0:resourcetype/><x0:displayname/><x0:owner/><x0:resourcetype/><x0:sync-token/><x0:current-user-privilege-set/><x0:getcontenttype/><x0:getetag/><x0:resourcetype/><x1:calendar-data/></x0:prop><x1:filter><x1:comp-filter name="VCALENDAR"><x1:comp-filter name="VTODO"><x1:prop-filter name="completed"/><x1:prop-filter name="related-to"><x1:text-match>7f88a43e-487c-11ea-a65d-902b34303921</x1:text-match></x1:prop-filter></x1:comp-filter></x1:comp-filter></x1:filter></x1:calendar-query>
```
I'm way out of my waters here to interpret the differences, but maybe someone else can. :)

**Comment by tobixen** [comment]
I'd like to see the response from the server as well

**Comment by tobixen** [comment]
Ok, failed to see this:

> Only if I query for a UID, the 207 just comes up empty.

... so then the response doesn't matter much.  I had a hypothesis that the code interpreting the results from the server was broken, but clearly that's not the problem here.

The differences between those two queries:

* The top query searches through all calendar items, the bottom one restricts it to completed tasks.  I haven't read what the RFC says on this, but perhaps it's needed to be explicit that it's a task and not a calendar event we want out.  It could also be that the server by default will only search through pending tasks and that it's needed to be explicit on this if one wants to fetch a completed task (but then again, the VTODO you pasted earlier says that the task is not completed.  weird).
* The top query searches for an item with a specific UID, the bottom query asks for a property "related-to".  Hm.  That's strange.  I should read through the RFC and see what it says about "related-to".
* The top query sets collation on the text match for the UID, the bottom query doesn't do this.  I don't think can be significant.

**Comment by tobixen** [comment]
I don't understand the "related-to"-thing. prop-filter is described at https://tools.ietf.org/html/rfc4791#section-9.7.2 ... as far as I can see, "related-to" is not a valid property of the given VTODO item.  The property related-to is described at https://tools.ietf.org/html/rfc5545#section-3.8.4.5 and, as one may expect, is used to indicate that one calendar item is related to another calendar item (it can also be used to cross the type boundary - VEVENTs can be related to TODO-items, etc)

There is an example for direct UID lookup at https://tools.ietf.org/html/rfc4791#section-7.8.6 ... it looks quite similar to the top query, except the missing comp-filter on VTODO.

So ... I'd like to see the return response on your successful query.  Perhaps it's not the same VTODO returned? :-)

**Comment by microbrewer** [comment]
It's even weirder ... the second query gets the same empty 207 response:
```
<?xml version="1.0"?>\n<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"/>
```
The other client has a graphical UI, so it queries and displays the entire list when I open it. The UID query gets fired when I open the details for an individual task. Since this worked, I just assumed the query succeeded. My hypothesis now is that the UID query is just used to verify that the task still exists at all, but the actual content is then retrieved locally.

**Comment by tobixen** [comment]
As said, that second query does not do a lookup on the UID-field, it does a lookup on the related-field, hence it's probably trying to see if there are any other vtodo-items on the task list that are related to the one it's showing.

**Comment by tobixen** [comment]
Perhaps the missing CompFilter (for telling the caldav server if it should look in calendar events or in todo tasks) is to blame.  I suspect this is a bug in the calendar-cli ...

**Comment by tobixen** [comment]
... can you try with the current master version of calendar-cli?

**Comment by microbrewer** [comment]
It works! :D

**Comment by tobixen** [comment]
wow.  awesome.

**Comment by microbrewer** [comment]
Thanks a lot!!!!
