### ISSUE TITLE
Directly instantiate Calendar object knowing the URL

### ISSUE THREAD

**Issue by cript0nauta** [python-caldav/caldav#8]
Hi, I noted that to get a Calendar instance I have to instantiate a client, then get a Principal and after that get the calendar. I logged the requests made and I saw that this process does 3 different requests to the server:
```
In [30]: c=caldav.DAVClient('https://user:pwd@myhost/nextcloud/remote.php/dav').principal().calendar(cal_id='mycalendar')
DEBUG:requests.packages.urllib3.connectionpool:https://myhost "PROPFIND /nextcloud/remote.php/dav/ HTTP/1.1" 401 555
DEBUG:requests.packages.urllib3.connectionpool:https://myhost "PROPFIND /nextcloud/remote.php/dav/ HTTP/1.1" 207 611
DEBUG:requests.packages.urllib3.connectionpool:https://myhost "PROPFIND /nextcloud/remote.php/dav/principals/users/myusername/ HTTP/1.1" 207 627

In [31]: c.url
Out[31]: URL(https://myhost/nextcloud/remote.php/dav/calendars/myusername/mycalendar)
```

I would like to skip this process if I already know the calendar URL to improve performance by instanciating Calendar directly, but I can't do it without getting an error:
```
In [40]: caldav.Calendar(url=c.url, name='name', id='id').events()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-40-911c65d16a1e> in <module>()
----> 1 caldav.Calendar(url=c.url, name='name', id='id').events()

/lib/python3.6/site-packages/caldav/objects.py in events(self)
    674         root = cdav.CalendarQuery() + [prop, filter]
    675 
--> 676         response = self._query(root, 1, query_method='report')
    677         results = self._handle_prop_response(response, props=[cdav.CalendarData()])
    678         for r in results:

/lib/python3.6/site-packages/caldav/objects.py in _query(self, root, depth, query_method, url, expected_return_value)
    124             body = etree.tostring(root.xmlelement(), encoding="utf-8",
    125                                   xml_declaration=True)
--> 126         ret = getattr(self.client, query_method)(
    127             url, body, depth)
    128         if ret.status == 404:

AttributeError: 'NoneType' object has no attribute 'report'
```
I also tried serializing the calendar instance using pickle, but I get a RecursionError exception when deserializing.

How do you recomend to achieve this? I don't want to do so many requests to get a simple list of events!

**Comment by tobixen** [comment]
calendar.client must be populated with a DAVClient object.  There is no network communication done in the initialization of the DAVClient object, everything happens when calling principal, hence you could get away with some construct like this:

    mycal = cald av.Calendar(client=caldav.DAVClient(....), ...)
    return mycal.events()

I don't have any time for this now, but the best would probably be to fix DAVObject.__init__ to  accept all parameters that DAVClient accepts, and initiate a DAVClient object if neither client nor parent is given in the input variables.  I'd happily accept a pull request if you can fix this.

**Comment by tobixen** [comment]
(If you think calendar objects should be serializable, then please create a separate issue for that)

**Comment by sh4r3m4n** [comment]
Ok, I'll try this way. Thanks for answering!

**Comment by tobixen** [comment]
I believe this issue is resolved, so I close it.  Although, arguably the interface should perhaps be made more intuitive.
