### ISSUE TITLE
patch to support ctags and etags, and to allow response.reason to be optional to support Debian 9 requests library

### ISSUE THREAD

**Issue by jimays** [python-caldav/caldav#81]
Hello,
Gratitude for an excellent library.  I have used it to integrate Odoo with iCloud Calendar.
I am not sure how you would prefer to receive this patch, perhaps you would like me to push it.

The patch adds basic support for ctags and etags and also has a small change to allow response.reason to be optional to support the requests library on Debian 9.
I could push as two commits or together, for ctags/etags and for requests.reason.

I am thankful to http://sabre.io/dav/building-a-caldav-client/ for informing me about ctags and etags.

Kind regards,
Jim

From 7d7195f97d8157006fb6ac7765763eec07cd9d10 Mon Sep 17 00:00:00 2001
From: root <root@odoo7-248.idsp56.net>
Date: Thu, 14 Nov 2019 10:16:12 -0700
Subject: [PATCH] add basic support for ctags and etags, and made
 "response.reason" optional to support requests library on
 Debian 9

---
 caldav/davclient.py       |    7 +++-
 caldav/elements/calsrv.py |   11 +++++++
 caldav/lib/namespace.py   |    3 ++
 caldav/objects.py         |   80 +++++++++++++++++++++++++++++++++++++--------
 4 files changed, 86 insertions(+), 15 deletions(-)
 create mode 100644 caldav/elements/calsrv.py

diff --git a/caldav/davclient.py b/caldav/davclient.py
index 37a5025..76e8bf0 100644
--- a/caldav/davclient.py
+++ b/caldav/davclient.py
@@ -37,7 +37,12 @@ class DAVResponse:
         self.raw = response.content
         self.headers = response.headers
         self.status = response.status_code
-        self.reason = response.reason
+        # 13.0.6.16.15-t3 jimays For some reason, responses are coming free of "reason" on Debian 9.
+        # self.reason = response.reason
+        try:
+            self.reason = response.reason
+        except:
+            pass
         log.debug("response headers: " + str(self.headers))
         log.debug("response status: " + str(self.status))
         log.debug("raw response: " + str(self.raw))
diff --git a/caldav/elements/calsrv.py b/caldav/elements/calsrv.py
new file mode 100644
index 0000000..0208c15
--- /dev/null
+++ b/caldav/elements/calsrv.py
@@ -0,0 +1,11 @@
+#!/usr/bin/env python
+# -*- encoding: utf-8 -*-
+# 13.0.6.17.16-t11 jimays added CS to support getctag
+
+from caldav.lib.namespace import ns
+from .base import BaseElement, ValuedBaseElement
+
+
+# Properties
+class GetCTag(ValuedBaseElement):
+    tag = ns("CS", "getctag")
diff --git a/caldav/lib/namespace.py b/caldav/lib/namespace.py
index b538737..c537a6d 100644
--- a/caldav/lib/namespace.py
+++ b/caldav/lib/namespace.py
@@ -15,6 +15,9 @@ nsmap2 = {
     "D": "DAV:",
     "C": "urn:ietf:params:xml:ns:caldav",
     "I": "http://apple.com/ns/ical/",
+    # 13.0.6.17.16-t11 jimays added CS to support getctag
+    # gratitude http://sabre.io/dav/building-a-caldav-client/ 
+    "CS": "http://calendarserver.org/ns/",
 }
 
 
diff --git a/caldav/objects.py b/caldav/objects.py
index b32b20a..017c61b 100644
--- a/caldav/objects.py
+++ b/caldav/objects.py
@@ -24,9 +24,12 @@ try:
 except:
     pass
 
+# 13.0.6.17.16-t11 jimays added minimal support for ctags and etags
+# gratitude http://sabre.io/dav/building-a-caldav-client/
+
 from caldav.lib import error, vcal
 from caldav.lib.url import URL
-from caldav.elements import dav, cdav
+from caldav.elements import dav, cdav, calsrv # 13.0.6.17.16-t11 jimays added calsrv to support getctag
 from caldav.lib.python_utilities import to_unicode
 
 
@@ -77,7 +80,9 @@ class DAVObject(object):
     def canonical_url(self):
         return str(self.url.unauth())
 
-    def children(self, type=None):
+    # 13.0.6.17.16-t11 jimays added extraprop to support getctag
+
+    def children(self, type=None, extraprop=None):
         """
         List children, using a propfind (resourcetype) on the parent object,
         at depth = 1.
@@ -88,6 +93,9 @@ class DAVObject(object):
         properties = {}
 
         props = [dav.ResourceType(), dav.DisplayName()]
+        # 13.0.6.17.16-t11 jimays added extraprop to support getctag
+        if extraprop:
+            props.append(extraprop)
         response = self._query_properties(props, depth)
         properties = self._handle_prop_response(
             response=response, props=props, type=type, what='tag')
@@ -95,6 +103,9 @@ class DAVObject(object):
         for path in list(properties.keys()):
             resource_type = properties[path][dav.ResourceType.tag]
             resource_name = properties[path][dav.DisplayName.tag]
+            # 13.0.6.17.16-t11 jimays added extraprop to support getctag
+            if extraprop:
+                resource_extraprop = properties[path][extraprop.tag]
 
             if resource_type == type or type is None:
                 # TODO: investigate the RFCs thoroughly - why does a "get
@@ -105,8 +116,13 @@ class DAVObject(object):
                 # to RFC 2518, section 5.2.
                 if (self.url.strip_trailing_slash() !=
                         self.url.join(path).strip_trailing_slash()):
-                    c.append((self.url.join(path), resource_type,
-                              resource_name))
+                    # 13.0.6.17.16-t11 jimays added extraprop to support getctag
+                    if extraprop:
+                        c.append((self.url.join(path), resource_type,
+                                  resource_name, resource_extraprop))
+                    else:
+			c.append((self.url.join(path), resource_type,
+				  resource_name))
 
         return c
 
@@ -286,6 +302,7 @@ class DAVObject(object):
 
 
 class CalendarSet(DAVObject):
+    # 13.0.6.17.16-t11 jimays updated to also retrieve the ctags
     def calendars(self):
         """
         List all calendar collections in this set.
@@ -295,9 +312,13 @@ class CalendarSet(DAVObject):
         """
         cals = []
 
-        data = self.children(cdav.Calendar.tag)
-        for c_url, c_type, c_name in data:
-            cals.append(Calendar(self.client, c_url, parent=self, name=c_name))
+        # 13.0.6.17.16-t11 jimays added extraprop to also retrieve the ctags
+        #data = self.children(cdav.Calendar.tag)
+        #for c_url, c_type, c_name in data:
+        #    cals.append(Calendar(self.client, c_url, parent=self, name=c_name))
+        data = self.children(cdav.Calendar.tag, extraprop=calsrv.GetCTag())
+        for c_url, c_type, c_name, c_ctag in data:
+            cals.append(Calendar(self.client, c_url, parent=self, name=c_name, ctag=c_ctag))
 
         return cals
 
@@ -427,6 +448,13 @@ class Calendar(DAVObject):
     The `Calendar` object is used to represent a calendar collection.
     Refer to the RFC for details: http://www.ietf.org/rfc/rfc4791.txt
     """
+
+    # 13.0.6.17.16-t11 jimays added __init__() to support getctag
+    def __init__(self, client=None, url=None, parent=None, name=None, id=None, ctag=None,
+                 **extra):
+        super(Calendar, self).__init__(client=client, url=url, parent=parent, name=name, id=id, **extra)
+        self.ctag = ctag
+
     def _create(self, name, id=None, supported_calendar_component_set=None):
         """
         Create a new calendar with display name `name` in `parent`.
@@ -809,7 +837,9 @@ class Calendar(DAVObject):
     # alias for backward compatibility
     event = event_by_uid
 
-    def events(self):
+    # 13.0.6.17.19-t1 jimays updated to also fetch etags, or with only_etags==True to only fetch etags
+
+    def events(self, only_etags=None):
         """
         List all events from the calendar.
 
@@ -818,7 +848,11 @@ class Calendar(DAVObject):
         """
         all = []
 
-        data = cdav.CalendarData()
+        # 13.0.6.17.19-t1 jimays also or only fetch etags
+        # data = cdav.CalendarData()
+        CalendarData = cdav.CalendarData()
+        GetEtag = dav.GetEtag()
+        data = [GetEtag] if only_etags else [GetEtag] + [CalendarData]
         prop = dav.Prop() + data
         vevent = cdav.CompFilter("VEVENT")
         vcalendar = cdav.CompFilter("VCALENDAR") + vevent
@@ -826,12 +860,26 @@ class Calendar(DAVObject):
         root = cdav.CalendarQuery() + [prop, filter]
 
         response = self._query(root, 1, query_method='report')
+        # 13.0.6.17.19-t1 jimays also or only fetch etags
+        # results = self._handle_prop_response(
+        #     response, props=[cdav.CalendarData()])
         results = self._handle_prop_response(
-            response, props=[cdav.CalendarData()])
+            response, props=data)
+        CalendarData_tag = cdav.CalendarData.tag
+        GetEtag_tag = dav.GetEtag.tag
         for r in results:
-            all.append(Event(
-                self.client, url=self.url.join(r),
-                data=results[r][cdav.CalendarData.tag], parent=self))
+            # 13.0.6.17.19-t1 jimays also or only save etags
+            #all.append(Event(
+            #    self.client, url=self.url.join(r),
+            #    data=results[r][cdav.CalendarData.tag], parent=self))
+            if only_etags:
+                all.append(Event(
+                    self.client, url=self.url.join(r),
+                    etag=results[r][GetEtag_tag], parent=self))
+            else:
+                all.append(Event(
+                    self.client, url=self.url.join(r),
+                    data=results[r][CalendarData_tag], etag=results[r][GetEtag_tag], parent=self))
 
         return all
 
@@ -873,7 +921,9 @@ class CalendarObjectResource(DAVObject):
     _vobject_instance = None
     _data = None
 
-    def __init__(self, client=None, url=None, data=None, parent=None, id=None):
+    # 13.0.6.17.19-t1 jimays added optional etag
+
+    def __init__(self, client=None, url=None, data=None, parent=None, etag=None, id=None):
         """
         CalendarObjectResource has an additional parameter for its constructor:
          * data = "...", vCal data for the event
@@ -881,6 +931,8 @@ class CalendarObjectResource(DAVObject):
         DAVObject.__init__(self, client=client, url=url, parent=parent, id=id)
         if data is not None:
             self.data = data
+        if etag is not None:
+            self.etag = etag
 
     def copy(self, keep_uid=False, new_parent=None):
         """
-- 
1.7.10.4

**Comment by jimays** [comment]
I am sorry. Clearly, pasting the patch into this box was a bad idea...
Here it is attached.  For comments or if you would like me to push the changes,
feel free to email me at jimays@theidsp.net.
Gratitude.
[0001-add-basic-support-for-ctags-and-etags-and-made-respo.patch.txt](https://github.com/python-caldav/caldav/files/3847872/0001-add-basic-support-for-ctags-and-etags-and-made-respo.patch.txt)

**Comment by tobixen** [comment]
There are ways of embedding code (and patches) in comments, like one line with only three backticks, eventually three backticks followed by the type of code, like this:

```patch
diff --git a/caldav/davclient.py b/caldav/davclient.py
index 37a5025..76e8bf0 100644
--- a/caldav/davclient.py
+++ b/caldav/davclient.py
@@ -37,7 +37,12 @@ class DAVResponse:
         self.raw = response.content
         self.headers = response.headers
         self.status = response.status_code
-        self.reason = response.reason
+        # 13.0.6.16.15-t3 jimays For some reason, responses are coming free of "reason" on Debian 9.
+        # self.reason = response.reason
+        try:
+            self.reason = response.reason
+        except:
+            pass
         log.debug("response headers: " + str(self.headers))
         log.debug("response status: " + str(self.status))
         log.debug("raw response: " + str(self.raw))
```
The github way of delivering patches is to make your own fork of the project, commit and push the changes to your own fork (best to use a separate branch for it), then find the buttons for "create pull request" from the github webui.  Anyway, I will look through the patch, hopefully already today.

**Comment by tobixen** [comment]
I will need to look more into the ctag stuff.  I would like to make a minor release before implementing support for ctag, as the last release contains bugs that have been fixed in the master branch.

**Comment by jimays** [comment]
Hi Tobias,

Apparently according to https://github.com/apple/ccs-calendarserver/blob/master/doc/Extensions/caldav-ctag.txt, I am not supposed to be using ctags at all.

Instead I'm supposed to use sync-collection reports as described in

https://tools.ietf.org/html/rfc6578

and also at the bottom of

http://sabre.io/dav/building-a-caldav-client/

where from the doc top I gleaned the info about ctags.

So I'm going to think about this some more.  My client needs me to sync automatically with her icloud cal, like by next week, so i have to do something, and with the number of clients who will want this feature, I must do something beyond fetching all events every 5 minutes.

I have your library hooked into Odoo up to the level of calendars discovery starting with a principal, and it's doing great.  I appreciate greatly.  Calendar names (and ctags) are retrieved nicely.  Nice library. I was prepared to use curl...

I expect I will choose to go for sync-collection instead of ctags.  The etags are still important.

Wondering if you have thought about sync-collection.

And yes, sure, I'll push a feature branch when it's time. Sorry about the weird pull request.

And gratitude again for responding so quickly.

Jim At Your Service

**Comment by tobixen** [comment]
I'll close this one and create another issue "support for sync-collection".
