### ISSUE TITLE
Failed to retrieve Principal:  401

### ISSUE THREAD

**Issue by guitar9** [python-caldav/caldav#84]
I am using nextcloud and I get this error. The url, username and password is correct. What I am doing wrong?

**Comment by guitar9** [comment]
I tried  icloud_example.py from example folder. Does somebody have example for nextcloud?

**Comment by tobixen** [comment]
caldav should work against nextcloud without any special tweaking.

401 either means the password/username was wrong (or perhaps the URL), or that the authorization failed for other reasons (which may be a problem with the library).

I don't have the time for assisting in debugging the issue today at least.

**Comment by tobixen** [comment]
The best example code is probably "hidden" in tests/test_caldav.py.  As soon as #3 is fixed once and for all that ical example file will be deleted.

**Comment by guitar9** [comment]
Thank you. I will try it later.

**Comment by guitar9** [comment]
I dont how to use  tests/test_caldav.py. Somebody has a simple skript for nextcloud?

**Comment by guitar9** [comment]
I tried also with this credentials. https://www.caldavserver.com/DAV

**Comment by guitar9** [comment]
With quickstart on documentation guide it works. 
https://pythonhosted.org/caldav/
