### ISSUE TITLE
how to get the date of an repeating event

### ISSUE THREAD

**Issue by kaykoch** [python-caldav/caldav#85]
Hi,
If I look for upcoming events (which repeats weekly)  within the next 2 days, I got the right events. But they are shown with the FIRST date, not with the NEXT date.
Today: 6. April 2020
     `DTSTART;TZID=Europe/Berlin:20190813T064000`
 `- > 2019-08-13 06:40:00+02:00`
Is there a possibility to get the the date-time for the event?
`-> 2020-04-07 06:40:00+02:00`

thanks

**Comment by tobixen** [comment]
Yes, it is possible - that's how it works when taking out the calendar agenda through the calendar-cli tool, it shows the first upcoming timestamp for the event.  The logic itself is performed by the caldav server, hence results may vary dependent on what server is used.

The relevant code line from the calendar-cli project looks like this:

    events_ = find_calendar(caldav_conn, args).date_search(dtstart, dtend, expand=True)

where dtstart is set to current timestamp and dtend is set to current timestamp + 30 days.
