### ISSUE TITLE
date_search(..., expand=True) should probably do a better job on expanding the icalendar data

### ISSUE THREAD

**Issue by tobixen** [python-caldav/caldav#86]
Reports has it (i.e. in #3) that the expand flag on calendar search does not always work. This should be investigated.

**Comment by tobixen** [comment]
See also #44 and https://github.com/tobixen/calendar-cli/issues/52

**Comment by tobixen** [comment]
So, I've concluded in this ...

* Some servers (xandikos, others?) does not support recurrences at all, so the event will only be found if searching for the first occurrence.  This is absolutely a server problem and will not be fixed in the caldav library.

* Some servers (radicale, others?) will find the object if any occurrences is within the timerange used in the search, but does not support expansion.  This is also something expected from the server or from a good icalendar library and outside the scope of the caldav library.

* Multiple single-time events found will be returned as a list of Event objects from date_search ... but an expanded reoccurring event will be returned as one Event object, one has to inspect the content to see that there is multiple vEvents in the data.  I've even expected myself that the expanded events will be delivered as independent objects in that list when creating the calendar-cli utility.

At one hand, this is very bad as it's neither intuitive nor documented.  At the other hand, I feel this is a bit outside the scope of the caldav library as it's related to handling of icalendar data, I would probably need to break backward compatibility to make it more intuitive, and I'm also concerned that it would add a lot of complexity to find a better solution to it.

My conclusion is that the current code is good enough for 0.7, but that some better solution should be found for 1.0.  In 1.0, I will probably switch from vobject to icalendar for handling the ical data.

**Comment by NicoHood** [comment]
I just stumbled across this issue. I have a radicale server and I want to get all expanded events for a specific week. If i understand your text correct, the library will do a server side search and radicale is doing a bad job here, right?

So for me to work around this issue I need to get all events and expand those myself, right? That looks like a lot of complicated work. Did you made some example code to filter such events maybe?

**Comment by tobixen** [comment]
> I just stumbled across this issue. I have a radicale server and I want to get all expanded events for a specific week. If i understand your text correct, the library will do a server side search and radicale is doing a bad job here, right?

Correct.

> So for me to work around this issue I need to get all events and expand those myself, right? That looks like a lot of complicated work. Did you made some example code to filter such events maybe?

No.

There is another python-based calendar server, xandikos, the latest version is supposed to support expanding.  Perhaps it's possible to use some code from that project.

Since this is a recurring issue with several calendar servers (even Google doesn't get it completely right), it may be within the scope of the caldav client library to work around those issues (adding methods for taking out the full calendar, checking the rrule towards the search timespan, filter out the relevant events and expand the recurrences) - but at least, I don't have any capacity for fixing that.

**Comment by NicoHood** [comment]
Maybe this library can help:
https://github.com/niccokunzmann/python-recurring-ical-events

**Comment by NicoHood** [comment]
I checked the example, however the library seems to expect an ics file as a whole. This library only outputs all events as an array of special objects. Is there a way to get them in the right ics format, so we can use the linked library?

**Comment by tobixen** [comment]
If you have a list of Event objects from the caldav library, you can turn it into a list of icalendar text objects like this (probably ... not tested):  `[o.data for o in events]`

**Comment by tobixen** [comment]
If you anyway need to fetch the full list of events and can fetch the whole calendar in one go through some ics URL, then ... indeed, there is probably no point in communicating with the calendar through the CalDAV protocol, and then it's probably no point using the caldav library indeed :-)

**Comment by tobixen** [comment]
I will close this issue and follow it up in #157.
