### ISSUE TITLE
Look into issues with documentation mirrors at readthedocs and pythonhosted.org

### ISSUE THREAD

**Issue by tobixen** [python-caldav/caldav#95]
* There is some documentation at https://packages.python.org/caldav/ - redirecting to https://pythonhosted.org/caldav/ - but I can't figure out how to update it.  It's old documentation, should be removed or updated.
* I've made https://readthedocs.org/projects/caldav/, it updates automatically, but there is a flaw there - the sphinx extentions to generate documentation from the source code doesn't work.  I think they should work also at readthedocs.  It should be looked into.

(ref #67)

**Comment by tobixen** [comment]
For readthedocs, the solution was quite simple ... in retro-perspective I should rather have been googling than trying to investigate with mock-commits ... it was just a switch "install project" that needed to be switched on in the readthedocs project advanced settings.  (Now I got a lot more work to do ... need to look through docstrings and classes and make sure the autogenerated documentation looks good).

**Comment by tobixen** [comment]
@cyrilrbt ... have a look at https://stackoverflow.com/questions/6521931/how-to-delete-documentation-from-pypi

The admin-button in pypi is shaded for me, I have no access there.

The 0.5.0-documentation at pythonhosted.org needs to be replaced with the current doc (on every release), replaced with a redirect to readthedocs, or destroyed.  The latter is probably easiest.  I'm not going to manually update any documentation.

**Comment by cyrilrbt** [comment]
I blew it up! Odd that as a maintainer role they didn't let you do it
