### ISSUE TITLE
release 0.7.0

### ISSUE THREAD

**Issue by tobixen** [python-caldav/caldav#97]
Version 0.7.0 is quite ready to be released now.  Possibly there will be an 0.8.0-version supporting sync-collection (ref #87), except for that the next will probably be 1.0 (see #92 for changes that may be introduced in 1.0, as well as the "1.0" milestone in the issue tracker).

## Updates since 0.6.2

As for real code changes - actually, not that much.  The library is relatively mature now - the remaining changes and issues are mostly either sufficiently significant that they should be procrastinated for a 1.0-release, or I consider them too insignificant to bother with it (except #87).  Here is the list:

* Some tweaks to support newer versions of Zimbra and other caldav server implementations with slightly twisted support for the RFC.
* API change: `add_event`, `add_todo` and `add_journal` methods are now deprecated and aliases of `save_*`.  New attributes `no_create` and `no_overwrite` if one wants to be sure the `save_*`-methods does the right thing.
* A calendar can be created without a display name
* Quite some minor bugfixes
* Some code refactoring, removing some duplicated code
* library will gracefully create an UID if fed with caldav data missing the UID field
* Earlier, for calendar servers not supporting the digest auth format, every request towards the server would be duplicated (try digest auth, retry basic auth).  I'm sure there is a more proper fix for it, but at least now it should only try digest auth once, and then save the authentication information.
* it's now possible to use the caldav library together with icalendar instances (but as of 0.7.0, vobject is still the officially supported icalendar library).
* the code has been reorganized making it possible for "power users" to do custom calendar searches.

Outside the library code there has been quite some work done;

* A python file has been stored in the examples folder, with quite some basic usage examples
* The documentation has been refreshed, manually copied some of the lines from that example file into the documentation.  Documentation has been uploaded to ReadTheDocs (but something is buggy there, as the autogenerated parts of the documentation isn't available there)
* Quite some work has been done on the test code - doing my best to uncover weird RFC incompatibilities from the servers tested as well as increasing code coverage.
* Quite some cleanup work in the github issues

## Checklist prior to release

* Need to test the code towards more server implementations, ref #45
* Should update the ChangeLog
* Should change the version number in setup.py
* Should make a tag v0.7.0 in the github repository
* Should push to pypi

Have I forgotten anything?  @cyrilrbt , comments? :-)

**Comment by cyrilrbt** [comment]
Sounds great!

**Comment by tobixen** [comment]
Quite ready for a release now.  I've executed the tests towards Zimbra (hm, worked some few days ago, does not work now, but I'm inclined to blame the server), Bedework, DAViCal (but old version of it), Radicale, Xandikos and Baikal.

**Comment by tobixen** [comment]
tagging and pushing to pypi postponed - it's late evening now, and I have a tendency to do mistakes in the late evenings.

**Comment by tobixen** [comment]
Released.  I hope I did everything correct, not using twine very often those days ...

**Comment by tobixen** [comment]
Note to self for 0.13 and/or 1.0: it's also a good idea to not only push a version tag to github, but also actively press the "make release"-button in the github web-ui.
