### ISSUE TITLE
How to access CalendarColor?

### ISSUE THREAD

**Issue by caco3** [python-caldav/caldav#98]
How do I get the calendar color? I see there is a function `CalendarColor` in https://github.com/python-caldav/caldav/blob/master/caldav/elements/ical.py#L8, how ever I could not figure out how to use it.

I can use `calendar.get_properties([caldav.dav.DisplayName()])` to get the name, so I tried `calendar.get_properties([caldav.icalendar.CalendarColor()])`. But that returns `AttributeError: module 'vobject.icalendar' has no attribute 'CalendarColor'`

I know hat it works, because I am able to access it through PHP: https://gitlab.rlm.pw/ralmn/nextdom-plugin-caldav/blob/aa05a4a045b04b614204cc5c7402dca0303f3bf5/3rdparty/simpleCalDAV/config/listCalendars.php#L48

**Comment by tobixen** [comment]
Calendar color is not part of RFC4791 and hence not officially supported. However, try caldav.elements.ical.CalendarColor

**Comment by tobixen** [comment]
Todo-items:

* Look into if there exists any rfc for this extention and document it
* Consider to let the ical elements be imported into the caldav namespace
* Currently the ical namespace is sent in every xml request, should probably try to avoid it when it's not used.
* Test code exercising the ical elements.

**Comment by tobixen** [comment]
The apple ical namespace seems to be completely undocumented, or at least its very well hidden, couldn't find anything through a quick Internet search now (somewhat handicapped as I'm trying to figure out things from my phone). However, I've learned that it's supported by many server implementations.

**Comment by caco3** [comment]
Thank you very much for your quick support!

Indeed it works with 
```
import caldav.elements.ical # for calendarColor
[..]
print(calendar.get_properties([caldav.elements.ical.CalendarColor()]))
```

**Comment by caco3** [comment]
For the resources, here what I found:
 * https://wiki.wocommunity.org/display/~probert/CalDAV+and+CardDAV+properties
 * https://sabre.io/dav/clients/ical/
 * https://tools.ietf.org/html/rfc7986#section-5.9

For the backend I use Nextcloud, which itself uses [Sabre\DAV](https://github.com/nextcloud/3rdparty/tree/master/sabre/dav).

Feel free to close or keep this issue open.

**Comment by tobixen** [comment]
None of the resources above tells anything about the calendar-color and calendar-order xml attributes as far as I can tell.  The URL http://www.apple.com/ns/ical (redirects to https and) gives a 404.  Still, several calendar server implementations seem to support those two attributes.  Anyway, I consider myself done now.
